"""Index definitions derived from resources (unique identifiers), query-pattern filters
(equality then range) and $vectorSearch stages, plus an idempotent bootstrap.

Run `python -m app.db.indexes [--wait]` to create them (deploy/seed bootstrap). The app also
creates them at startup when CREATE_INDEXES=true; failures are logged, never fatal.

GENERATED by the backend coding agent - do not edit (read-only, verified by G8)."""

from __future__ import annotations

import asyncio
import copy
import logging
import sys
import time
from typing import Any

from pymongo import IndexModel
from pymongo.asynchronous.database import AsyncDatabase
from pymongo.errors import OperationFailure, PyMongoError
from pymongo.operations import SearchIndexModel

from app.db.base import Document

logger = logging.getLogger("app.db.indexes")

INDEXES: dict[str, list[dict[str, Any]]] = {
    "tenants": [{"keys": [("tenant_key", 1)], "unique": True, "name": "uk_tenant_key"}],
    "documents": [
        {
            "keys": [("tenant_id", 1), ("ingest_status", 1), ("document_type", 1)],
            "unique": False,
            "name": "idx_documents_tenant_status_type",
        },
        {
            "keys": [("tenant_id", 1), ("source_system", 1), ("created_at", 1)],
            "unique": False,
            "name": "idx_documents_tenant_source",
        },
        {
            "keys": [("tenant_id", 1), ("structured_attributes", 1)],
            "unique": False,
            "name": "idx_documents_structured_attrs",
        },
    ],
    "chunk_profiles": [
        {
            "keys": [("strategy", 1), ("is_active", 1)],
            "unique": False,
            "name": "idx_chunk_profiles_strategy",
        }
    ],
    "chunks": [
        {
            "keys": [("document_id", 1), ("chunk_profile_id", 1), ("chunk_index", 1)],
            "unique": False,
            "name": "idx_chunks_document_profile_order",
        },
        {
            "keys": [("tenant_id", 1), ("chunk_profile_id", 1)],
            "unique": False,
            "name": "idx_chunks_tenant_profile",
        },
    ],
    "queries": [
        {
            "keys": [("benchmark_run_id", 1), ("query_type", 1), ("created_at", 1)],
            "unique": False,
            "name": "idx_queries_run_type",
        },
        {
            "keys": [("tenant_id", 1), ("created_at", 1)],
            "unique": False,
            "name": "idx_queries_tenant_created",
        },
    ],
    "benchmark_runs": [
        {
            "keys": [("tenant_id", 1), ("status", 1), ("created_at", 1)],
            "unique": False,
            "name": "idx_benchmark_runs_tenant_status",
        }
    ],
    "query_results": [
        {
            "keys": [
                ("benchmark_run_id", 1),
                ("query_id", 1),
                ("approach", 1),
                ("chunk_profile_id", 1),
            ],
            "unique": False,
            "name": "idx_results_run_query_approach_profile",
        },
        {
            "keys": [("tenant_id", 1), ("approach", 1), ("created_at", 1)],
            "unique": False,
            "name": "idx_results_tenant_approach_created",
        },
    ],
}

SEARCH_INDEXES: dict[str, list[dict[str, Any]]] = {
    "chunks": [
        {
            "name": "search_chunks_text",
            "type": "search",
            "definition": {
                "mappings": {
                    "dynamic": False,
                    "fields": {
                        "text": {"type": "string"},
                        "structured_attributes": {"type": "document", "dynamic": True},
                        "chunk_profile_id": {"type": "objectId"},
                        "tenant_id": {"type": "objectId"},
                    },
                }
            },
        },
        {
            "name": "vector_chunks_embedding",
            "type": "vectorSearch",
            "definition": {
                "fields": [
                    {
                        "type": "vector",
                        "path": "embedding",
                        "numDimensions": "__DIMENSIONS__",
                        "similarity": "cosine",
                    },
                    {"type": "filter", "path": "chunk_profile_id"},
                    {"type": "filter", "path": "document_id"},
                    {"type": "filter", "path": "structured_attributes.memory_type"},
                    {"type": "filter", "path": "tenant_id"},
                ]
            },
        },
    ]
}


def _with_dimensions(definition: dict[str, Any], dimensions: int) -> dict[str, Any]:
    resolved = copy.deepcopy(definition)
    for field in resolved.get("fields", []):
        if field.get("numDimensions") == "__DIMENSIONS__":
            field["numDimensions"] = dimensions
    return resolved


async def ensure_indexes(db: AsyncDatabase[Document], vector_dimensions: int) -> None:
    for collection, specs in INDEXES.items():
        models = [
            IndexModel(spec["keys"], name=spec["name"], unique=spec["unique"]) for spec in specs
        ]
        try:
            await db[collection].create_indexes(models)
        except PyMongoError as error:
            logger.warning("index creation failed for %s: %s", collection, error)
    for collection, specs in SEARCH_INDEXES.items():
        try:
            existing = {item["name"] async for item in await db[collection].list_search_indexes()}
        except PyMongoError as error:
            logger.warning("search indexes unavailable for %s (not Atlas?): %s", collection, error)
            continue
        for spec in specs:
            if spec["name"] in existing:
                continue
            model = SearchIndexModel(
                definition=_with_dimensions(spec["definition"], vector_dimensions),
                name=spec["name"],
                type=spec.get("type", "vectorSearch"),
            )
            try:
                await db[collection].create_search_index(model)
            except (OperationFailure, PyMongoError) as error:
                logger.warning("search index %s failed on %s: %s", spec["name"], collection, error)


async def wait_for_search_indexes(
    db: AsyncDatabase[Document], timeout_seconds: float = 180
) -> bool:
    deadline = time.monotonic() + timeout_seconds
    while time.monotonic() < deadline:
        pending = 0
        for collection, specs in SEARCH_INDEXES.items():
            names = {spec["name"] for spec in specs}
            async for item in await db[collection].list_search_indexes():
                if item["name"] in names and not item.get("queryable"):
                    pending += 1
        if pending == 0:
            return True
        await asyncio.sleep(5)
    return False


async def _main(wait: bool) -> int:
    from app.db.client import create_client, get_db
    from app.settings import get_settings

    settings = get_settings()
    client = create_client(settings)
    try:
        db = get_db(client, settings)
        await ensure_indexes(db, settings.VECTOR_DIMENSIONS)
        if wait and SEARCH_INDEXES and not await wait_for_search_indexes(db):
            logger.error("search indexes not queryable before timeout")
            return 1
    finally:
        await client.close()
    return 0


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    sys.exit(asyncio.run(_main("--wait" in sys.argv)))
