"""Query-pattern builders. Pipelines are copied VERBATIM from query_patterns.json; only
placeholders (and documented `limit` values) are bound to typed parameters; omitted optional
conditions are pruned.

GENERATED by the backend coding agent - do not edit (read-only; G9 checks it against the spec)."""

from __future__ import annotations

from datetime import datetime
from typing import Any, Final, TypedDict, cast

from bson import ObjectId

Pipeline = list[dict[str, Any]]


class FindQuery(TypedDict):
    filter: dict[str, Any]
    projection: dict[str, Any] | None
    sort: dict[str, Any] | None
    limit: int | None


class _Omit:
    """Marks an optional condition whose value was not supplied."""


OMIT: Final = _Omit()


class Splice(list[Any]):
    """A caller-supplied list of clauses spliced into the surrounding list."""


def optional(value: Any) -> Any:
    """`<optionalX>` placeholders: None removes the enclosing condition."""
    return OMIT if value is None else value


def fragment(value: Any) -> Any:
    """Fragment placeholders: None removes the clause, a list is spliced, a dict is inserted."""
    if value is None:
        return OMIT
    if isinstance(value, list):
        return Splice(cast(list[Any], value))
    return value


def _prune(node: Any) -> tuple[Any, bool]:
    if isinstance(node, dict):
        kept: dict[str, Any] = {}
        removed = False
        for key, value in cast(dict[str, Any], node).items():
            pruned, gone = _prune(value)
            if gone:
                removed = True
                continue
            kept[key] = pruned
        return kept, removed and not kept
    if isinstance(node, list) and not isinstance(node, Splice):
        items: list[Any] = []
        removed = False
        for item in cast(list[Any], node):
            if isinstance(item, Splice):
                items.extend(item)
                continue
            pruned, gone = _prune(item)
            if gone:
                removed = True
                continue
            items.append(pruned)
        return items, removed and not items
    return node, isinstance(node, _Omit)


def prune(node: Any) -> Any:
    """Drop omitted optional conditions (and containers they leave empty, e.g. an empty `$or`)."""
    pruned, _ = _prune(node)
    return pruned


def qp_1(*, tenant_id: ObjectId, page_size: int, start_date: datetime | None = None) -> FindQuery:
    """QP-1 - List retrieval-ready documents for a tenant demo session. Show uploaded or connected documents that are ready for retrieval within a tenant-scoped POV/demo session."""
    return cast(
        FindQuery,
        prune(
            {
                "filter": {
                    "tenant_id": tenant_id,
                    "ingest_status": "embedded",
                    "document_type": {
                        "$in": [
                            "pdf",
                            "csv",
                            "google_sheet",
                            "text",
                            "slack_thread",
                            "confluence_page",
                            "jira_ticket",
                            "agent_memory",
                            "other",
                        ]
                    },
                    "source_system": {
                        "$in": [
                            "upload",
                            "s3",
                            "slack",
                            "confluence",
                            "jira",
                            "google_sheets",
                            "csv",
                            "pdf",
                            "agent_conversation",
                            "other",
                        ]
                    },
                    "created_at": {"$gte": optional(start_date)},
                },
                "projection": {
                    "title": 1,
                    "file_name": 1,
                    "document_type": 1,
                    "source_system": 1,
                    "source_uri": 1,
                    "structured_attributes": 1,
                    "is_agent_memory": 1,
                    "created_at": 1,
                },
                "sort": {"created_at": -1},
                "limit": page_size,
            }
        ),
    )


def qp_2(*, tenant_id: ObjectId, page_size: int, start_date: datetime | None = None) -> FindQuery:
    """QP-2 - Inspect document ingest pipeline status and failures. Monitor whether on-the-fly uploaded documents have been extracted, chunked, embedded, or failed during the demo workflow."""
    return cast(
        FindQuery,
        prune(
            {
                "filter": {
                    "tenant_id": tenant_id,
                    "ingest_status": {
                        "$in": ["uploaded", "text_extracted", "chunked", "embedded", "failed"]
                    },
                    "created_at": {"$gte": optional(start_date)},
                },
                "projection": {
                    "title": 1,
                    "file_name": 1,
                    "document_type": 1,
                    "source_system": 1,
                    "ingest_status": 1,
                    "ingest_errors": 1,
                    "updated_at": 1,
                },
                "sort": {"updated_at": -1},
                "limit": page_size,
            }
        ),
    )


def qp_3(*, tenant_id: ObjectId) -> FindQuery:
    """QP-3 - Retrieve chunk profiles available for comparison. List the chunking strategies configured for the POV so users can compare fixed, recursive, semantic, and contextual chunking."""
    return {
        "filter": {
            "is_active": True,
            "$or": [{"tenant_id": tenant_id}, {"tenant_id": None}],
            "strategy": {"$in": ["fixed_length", "recursive", "semantic", "contextual"]},
        },
        "projection": {"name": 1, "strategy": 1, "parameters": 1, "tenant_id": 1},
        "sort": {"strategy": 1, "name": 1},
        "limit": None,
    }


def qp_4(
    *,
    query_embedding: list[float],
    num_candidates: int,
    top_k: int,
    tenant_id: ObjectId,
    chunk_profile_id: ObjectId,
    document_ids: list[ObjectId] | None = None,
    user_id: ObjectId | None = None,
    group_ids: list[ObjectId] | None = None,
) -> Pipeline:
    """QP-4 - Vector retrieve chunks for document search. Run semantic vector search over chunk embeddings and return the most relevant tenant-scoped chunks for an uploaded document question."""
    return cast(
        Pipeline,
        prune(
            [
                {
                    "$vectorSearch": {
                        "index": "vector_chunks_embedding",
                        "path": "embedding",
                        "queryVector": query_embedding,
                        "numCandidates": num_candidates,
                        "limit": top_k,
                        "filter": {
                            "tenant_id": tenant_id,
                            "chunk_profile_id": chunk_profile_id,
                            "document_id": {"$in": optional(document_ids)},
                        },
                    }
                },
                {
                    "$project": {
                        "document_id": 1,
                        "chunk_profile_id": 1,
                        "text": 1,
                        "structured_attributes": 1,
                        "score": {"$meta": "vectorSearchScore"},
                    }
                },
                {
                    "$lookup": {
                        "from": "documents",
                        "localField": "document_id",
                        "foreignField": "_id",
                        "as": "document",
                    }
                },
                {"$unwind": "$document"},
                {
                    "$match": {
                        "$and": [
                            {"document.tenant_id": tenant_id},
                            {"document.ingest_status": "embedded"},
                            {
                                "$or": [
                                    {"document.access.user_ids": optional(user_id)},
                                    {"document.access.group_ids": {"$in": optional(group_ids)}},
                                    {"document.access": {"$exists": False}},
                                ]
                            },
                        ]
                    }
                },
                {
                    "$project": {
                        "chunk_id": "$_id",
                        "document_id": 1,
                        "score": 1,
                        "text_snippet": {"$substrCP": ["$text", 0, 500]},
                        "source_title": "$document.title",
                        "document_type": "$document.document_type",
                        "source_system": "$document.source_system",
                        "structured_attributes": 1,
                    }
                },
                {"$sort": {"score": -1}},
                {"$limit": top_k},
            ]
        ),
    )


def qp_5(
    *,
    query_text: str,
    tenant_id: ObjectId,
    chunk_profile_id: ObjectId,
    top_k: int,
    metadata_filters: dict[str, Any] | list[dict[str, Any]] | None = None,
    document_scope_filters: dict[str, Any] | list[dict[str, Any]] | None = None,
) -> Pipeline:
    """QP-5 - Hybrid lexical plus metadata retrieval over chunks. Retrieve chunks using text search combined with structured metadata filters to support hybrid structured and unstructured retrieval."""
    return cast(
        Pipeline,
        prune(
            [
                {
                    "$search": {
                        "index": "search_chunks_text",
                        "compound": {
                            "must": [{"text": {"query": query_text, "path": "text"}}],
                            "filter": [
                                {"equals": {"path": "tenant_id", "value": tenant_id}},
                                {"equals": {"path": "chunk_profile_id", "value": chunk_profile_id}},
                                fragment(metadata_filters),
                                fragment(document_scope_filters),
                            ],
                        },
                    }
                },
                {
                    "$project": {
                        "document_id": 1,
                        "text": 1,
                        "structured_attributes": 1,
                        "score": {"$meta": "searchScore"},
                    }
                },
                {
                    "$lookup": {
                        "from": "documents",
                        "localField": "document_id",
                        "foreignField": "_id",
                        "as": "document",
                    }
                },
                {"$unwind": "$document"},
                {"$match": {"document.ingest_status": "embedded"}},
                {
                    "$project": {
                        "chunk_id": "$_id",
                        "document_id": 1,
                        "score": 1,
                        "text_snippet": {"$substrCP": ["$text", 0, 500]},
                        "source_title": "$document.title",
                        "document_type": "$document.document_type",
                        "structured_attributes": 1,
                    }
                },
                {"$sort": {"score": -1}},
                {"$limit": top_k},
            ]
        ),
    )


def qp_6(
    *,
    query_embedding: list[float],
    num_candidates: int,
    top_k: int,
    tenant_id: ObjectId,
    chunk_profile_id: ObjectId,
    user_id: ObjectId,
    group_ids: list[ObjectId],
    memory_type: str | None = None,
) -> Pipeline:
    """QP-6 - Agent memory retrieval for a tenant. Fetch relevant conversation-derived memory chunks for an agent while honoring tenant and optional document-level access tags."""
    return cast(
        Pipeline,
        prune(
            [
                {
                    "$vectorSearch": {
                        "index": "vector_chunks_embedding",
                        "path": "embedding",
                        "queryVector": query_embedding,
                        "numCandidates": num_candidates,
                        "limit": top_k,
                        "filter": {
                            "tenant_id": tenant_id,
                            "chunk_profile_id": chunk_profile_id,
                            "structured_attributes.memory_type": optional(memory_type),
                        },
                    }
                },
                {
                    "$lookup": {
                        "from": "documents",
                        "localField": "document_id",
                        "foreignField": "_id",
                        "as": "document",
                    }
                },
                {"$unwind": "$document"},
                {
                    "$match": {
                        "document.is_agent_memory": True,
                        "document.tenant_id": tenant_id,
                        "$or": [
                            {"document.access.user_ids": user_id},
                            {"document.access.group_ids": {"$in": group_ids}},
                            {"document.access": {"$exists": False}},
                        ],
                    }
                },
                {
                    "$project": {
                        "chunk_id": "$_id",
                        "document_id": "$document._id",
                        "score": {"$meta": "vectorSearchScore"},
                        "text_snippet": {"$substrCP": ["$text", 0, 500]},
                        "source_title": "$document.title",
                        "structured_attributes": 1,
                        "created_at": "$document.created_at",
                    }
                },
                {"$sort": {"score": -1}},
                {"$limit": top_k},
            ]
        ),
    )


def qp_7(*, document_id: ObjectId, chunk_profile_id: ObjectId) -> Pipeline:
    """QP-7 - Get ordered chunks for a document under a specific chunking strategy. Inspect how a document was split into chunks for a given strategy, useful for explaining retrieval behavior during the benchmark/demo."""
    return [
        {"$match": {"document_id": document_id, "chunk_profile_id": chunk_profile_id}},
        {"$sort": {"chunk_index": 1}},
        {
            "$lookup": {
                "from": "chunk_profiles",
                "localField": "chunk_profile_id",
                "foreignField": "_id",
                "as": "chunk_profile",
            }
        },
        {"$unwind": "$chunk_profile"},
        {
            "$project": {
                "document_id": 1,
                "chunk_index": 1,
                "text": 1,
                "token_count": 1,
                "char_count": 1,
                "chunk_profile.name": 1,
                "chunk_profile.strategy": 1,
                "chunk_profile.parameters": 1,
            }
        },
    ]


def qp_8(*, tenant_id: ObjectId, page_size: int) -> FindQuery:
    """QP-8 - List benchmark runs for a tenant. Show available POV benchmark sessions and their status for a tenant/customer."""
    return {
        "filter": {
            "tenant_id": tenant_id,
            "status": {"$in": ["draft", "running", "completed", "failed"]},
        },
        "projection": {
            "name": 1,
            "status": 1,
            "comparison_targets": 1,
            "chunk_profile_ids": 1,
            "top_k_values": 1,
            "started_at": 1,
            "completed_at": 1,
            "created_at": 1,
        },
        "sort": {"created_at": -1},
        "limit": page_size,
    }


def qp_9(*, tenant_id: ObjectId, benchmark_run_id: ObjectId) -> FindQuery:
    """QP-9 - List queries for a benchmark run. Retrieve the benchmark question set and associated ground truth references for a specific POV run."""
    return {
        "filter": {
            "tenant_id": tenant_id,
            "benchmark_run_id": benchmark_run_id,
            "query_type": "benchmark",
        },
        "projection": {
            "query_text": 1,
            "expected_answer_text": 1,
            "ground_truth_chunk_ids": 1,
            "ground_truth_document_ids": 1,
            "document_scope": 1,
            "created_at": 1,
        },
        "sort": {"created_at": 1},
        "limit": None,
    }


def qp_10(*, tenant_id: ObjectId, benchmark_run_id: ObjectId, query_id: ObjectId) -> Pipeline:
    """QP-10 - Side-by-side results for one query across approaches and chunk profiles. Compare the returned top-k results, latency, and metrics for one benchmark query across MongoDB/Voyage and baseline systems."""
    return [
        {
            "$match": {
                "tenant_id": tenant_id,
                "benchmark_run_id": benchmark_run_id,
                "query_id": query_id,
                "approach": {
                    "$in": [
                        "mongodb_voyage",
                        "elastic",
                        "opensearch",
                        "qdrant",
                        "rudimentary_baseline",
                        "other",
                    ]
                },
            }
        },
        {
            "$lookup": {
                "from": "chunk_profiles",
                "localField": "chunk_profile_id",
                "foreignField": "_id",
                "as": "chunk_profile",
            }
        },
        {"$unwind": {"path": "$chunk_profile", "preserveNullAndEmptyArrays": True}},
        {
            "$project": {
                "approach": 1,
                "retrieval_mode": 1,
                "latency_ms": 1,
                "top_k_requested": 1,
                "results": 1,
                "metrics": 1,
                "chunk_profile": {
                    "name": "$chunk_profile.name",
                    "strategy": "$chunk_profile.strategy",
                },
            }
        },
        {"$sort": {"approach": 1, "chunk_profile.strategy": 1}},
    ]


def qp_11(*, tenant_id: ObjectId, benchmark_run_id: ObjectId) -> Pipeline:
    """QP-11 - Benchmark summary by approach for a run. Produce aggregate benchmark metrics per approach and top-k level, including precision, recall, ranking quality, and average latency."""
    return [
        {"$match": {"tenant_id": tenant_id, "benchmark_run_id": benchmark_run_id}},
        {
            "$group": {
                "_id": {
                    "approach": "$approach",
                    "retrieval_mode": "$retrieval_mode",
                    "chunk_profile_id": "$chunk_profile_id",
                    "top_k_requested": "$top_k_requested",
                },
                "avg_latency_ms": {"$avg": "$latency_ms"},
                "query_count": {"$sum": 1},
                "avg_mrr": {"$avg": "$metrics.mrr"},
                "avg_ndcg": {"$avg": "$metrics.ndcg"},
                "avg_precision_at_1": {"$avg": "$metrics.precision_at_k.1"},
                "avg_precision_at_5": {"$avg": "$metrics.precision_at_k.5"},
                "avg_precision_at_10": {"$avg": "$metrics.precision_at_k.10"},
                "avg_precision_at_20": {"$avg": "$metrics.precision_at_k.20"},
                "avg_recall_at_1": {"$avg": "$metrics.recall_at_k.1"},
                "avg_recall_at_5": {"$avg": "$metrics.recall_at_k.5"},
                "avg_recall_at_10": {"$avg": "$metrics.recall_at_k.10"},
                "avg_recall_at_20": {"$avg": "$metrics.recall_at_k.20"},
            }
        },
        {"$sort": {"_id.approach": 1, "_id.top_k_requested": 1}},
    ]


def qp_12(*, tenant_id: ObjectId, benchmark_run_id: ObjectId) -> Pipeline:
    """QP-12 - Detect queries where MongoDB/Voyage outperforms baseline. Identify benchmark questions where MongoDB/Voyage beats a comparison target on relevance and/or latency."""
    return [
        {
            "$match": {
                "tenant_id": tenant_id,
                "benchmark_run_id": benchmark_run_id,
                "approach": {
                    "$in": [
                        "mongodb_voyage",
                        "elastic",
                        "opensearch",
                        "qdrant",
                        "rudimentary_baseline",
                        "other",
                    ]
                },
            }
        },
        {
            "$project": {
                "query_id": 1,
                "approach": 1,
                "latency_ms": 1,
                "mrr": "$metrics.mrr",
                "ndcg": "$metrics.ndcg",
                "precision_at_5": "$metrics.precision_at_k.5",
                "recall_at_5": "$metrics.recall_at_k.5",
            }
        },
        {
            "$group": {
                "_id": "$query_id",
                "by_approach": {
                    "$push": {
                        "approach": "$approach",
                        "latency_ms": "$latency_ms",
                        "mrr": "$mrr",
                        "ndcg": "$ndcg",
                        "precision_at_5": "$precision_at_5",
                        "recall_at_5": "$recall_at_5",
                    }
                },
            }
        },
        {
            "$project": {
                "by_approach": 1,
                "mongodb_voyage": {
                    "$first": {
                        "$filter": {
                            "input": "$by_approach",
                            "as": "r",
                            "cond": {"$eq": ["$$r.approach", "mongodb_voyage"]},
                        }
                    }
                },
                "baseline": {
                    "$first": {
                        "$filter": {
                            "input": "$by_approach",
                            "as": "r",
                            "cond": {
                                "$in": [
                                    "$$r.approach",
                                    [
                                        "elastic",
                                        "opensearch",
                                        "qdrant",
                                        "rudimentary_baseline",
                                        "other",
                                    ],
                                ]
                            },
                        }
                    }
                },
            }
        },
        {
            "$project": {
                "mongodb_voyage": 1,
                "baseline": 1,
                "is_better_on_mrr": {"$gt": ["$mongodb_voyage.mrr", "$baseline.mrr"]},
                "is_better_on_ndcg": {"$gt": ["$mongodb_voyage.ndcg", "$baseline.ndcg"]},
                "is_better_on_precision_at_5": {
                    "$gt": ["$mongodb_voyage.precision_at_5", "$baseline.precision_at_5"]
                },
                "is_better_on_recall_at_5": {
                    "$gt": ["$mongodb_voyage.recall_at_5", "$baseline.recall_at_5"]
                },
                "is_lower_latency": {"$lt": ["$mongodb_voyage.latency_ms", "$baseline.latency_ms"]},
            }
        },
    ]


def qp_13(*, tenant_id: ObjectId, page_size: int, start_date: datetime | None = None) -> FindQuery:
    """QP-13 - Recent ad hoc query history for a tenant. Show recent interactive questions asked during a demo session for document search or agent memory exploration."""
    return cast(
        FindQuery,
        prune(
            {
                "filter": {
                    "tenant_id": tenant_id,
                    "query_type": "ad_hoc",
                    "created_at": {"$gte": optional(start_date)},
                },
                "projection": {
                    "query_text": 1,
                    "document_scope": 1,
                    "created_by": 1,
                    "created_at": 1,
                },
                "sort": {"created_at": -1},
                "limit": page_size,
            }
        ),
    )


def qp_14(*, benchmark_run_id: ObjectId, tenant_id: ObjectId) -> Pipeline:
    """QP-14 - Benchmark run detail with chunk profile definitions. Retrieve the benchmark configuration, including which systems and chunking strategies are being compared in the POV."""
    return [
        {"$match": {"_id": benchmark_run_id, "tenant_id": tenant_id}},
        {
            "$lookup": {
                "from": "chunk_profiles",
                "localField": "chunk_profile_ids",
                "foreignField": "_id",
                "as": "chunk_profiles",
            }
        },
        {
            "$project": {
                "name": 1,
                "status": 1,
                "comparison_targets": 1,
                "top_k_values": 1,
                "notes": 1,
                "started_at": 1,
                "completed_at": 1,
                "chunk_profiles": {"_id": 1, "name": 1, "strategy": 1, "parameters": 1},
            }
        },
    ]
