"""FastAPI dependency that builds the repositories for a request.

GENERATED by the backend coding agent - do not edit (read-only, verified by G8)."""

from __future__ import annotations

from fastapi import Request

from app.db.repositories import Repositories


def get_repositories(request: Request) -> Repositories:
    return Repositories(request.app.state.db)
