"""Contract tests for `queries` (G6): success, every declared error code, validation -> 400.

GENERATED by the backend coding agent - do not edit."""

from __future__ import annotations

from typing import Any

import pytest

from app.api.deps import get_queries_service
from app.api.schemas import (
    CreateQueryRequest,
    CreateQueryResponse,
    ListBenchmarkQueriesResponse,
    ListRecentAdHocQueriesResponse,
)
from app.errors import BenchmarkRunNotFound, InvalidId, TenantNotFound, ValidationError
from app.services.queries import QueriesService
from tests.support.factories import to_json_payload
from tests.support.fakes import FakeService, raising

URL_CREATE_QUERY = "/api/v1/tenants/65a1b2c3d4e5f60718293a4b/queries"
QUERY_CREATE_QUERY: dict[str, Any] = {}


async def test_create_query_success(client_factory: Any) -> None:
    fake = FakeService(QueriesService)
    client = client_factory({get_queries_service: fake})
    url = URL_CREATE_QUERY
    response = await client.request(
        "POST", url, params=QUERY_CREATE_QUERY, json=to_json_payload(CreateQueryRequest)
    )
    assert response.status_code == 201, response.text
    CreateQueryResponse.model_validate(response.json())
    assert fake.calls and fake.calls[0][0] == "create_query"


@pytest.mark.parametrize(
    "error",
    [ValidationError(), TenantNotFound(), BenchmarkRunNotFound()],
    ids=lambda e: type(e).__name__,
)
async def test_create_query_declared_errors(client_factory: Any, error: Any) -> None:
    fake = FakeService(QueriesService, {"create_query": raising(error)})
    client = client_factory({get_queries_service: fake})
    url = URL_CREATE_QUERY
    response = await client.request(
        "POST", url, params=QUERY_CREATE_QUERY, json=to_json_payload(CreateQueryRequest)
    )
    assert response.status_code == error.status_code, response.text
    assert response.json()["code"] == error.code


async def test_create_query_validation_empty_body(client_factory: Any) -> None:
    fake = FakeService(QueriesService)
    client = client_factory({get_queries_service: fake})
    url = URL_CREATE_QUERY
    response = await client.request("POST", url, params=QUERY_CREATE_QUERY, json={})
    assert response.status_code == 400, response.text
    assert response.json()["code"] in ["VALIDATION_ERROR"]
    assert not fake.calls


URL_LIST_RECENT_AD_HOC_QUERIES = "/api/v1/tenants/65a1b2c3d4e5f60718293a4b/queries/history"
QUERY_LIST_RECENT_AD_HOC_QUERIES: dict[str, Any] = {"created_after": "2026-01-01T00:00:00Z"}


async def test_list_recent_ad_hoc_queries_success(client_factory: Any) -> None:
    fake = FakeService(QueriesService)
    client = client_factory({get_queries_service: fake})
    url = URL_LIST_RECENT_AD_HOC_QUERIES
    response = await client.request("GET", url, params=QUERY_LIST_RECENT_AD_HOC_QUERIES)
    assert response.status_code == 200, response.text
    ListRecentAdHocQueriesResponse.model_validate(response.json())
    assert fake.calls and fake.calls[0][0] == "list_recent_ad_hoc_queries"


@pytest.mark.parametrize("error", [ValidationError()], ids=lambda e: type(e).__name__)
async def test_list_recent_ad_hoc_queries_declared_errors(client_factory: Any, error: Any) -> None:
    fake = FakeService(QueriesService, {"list_recent_ad_hoc_queries": raising(error)})
    client = client_factory({get_queries_service: fake})
    url = URL_LIST_RECENT_AD_HOC_QUERIES
    response = await client.request("GET", url, params=QUERY_LIST_RECENT_AD_HOC_QUERIES)
    assert response.status_code == error.status_code, response.text
    assert response.json()["code"] == error.code


async def test_list_recent_ad_hoc_queries_validation_created_after_malformed(
    client_factory: Any,
) -> None:
    fake = FakeService(QueriesService)
    client = client_factory({get_queries_service: fake})
    url = URL_LIST_RECENT_AD_HOC_QUERIES
    query = dict(QUERY_LIST_RECENT_AD_HOC_QUERIES)
    query["created_after"] = "not-a-date"
    response = await client.request("GET", url, params=query)
    assert response.status_code == 400, response.text
    assert response.json()["code"] == "VALIDATION_ERROR"
    assert not fake.calls


async def test_list_recent_ad_hoc_queries_validation_limit_not_numeric(client_factory: Any) -> None:
    fake = FakeService(QueriesService)
    client = client_factory({get_queries_service: fake})
    url = URL_LIST_RECENT_AD_HOC_QUERIES
    query = dict(QUERY_LIST_RECENT_AD_HOC_QUERIES)
    query["limit"] = "abc"
    response = await client.request("GET", url, params=query)
    assert response.status_code == 400, response.text
    assert response.json()["code"] == "VALIDATION_ERROR"
    assert not fake.calls


URL_LIST_BENCHMARK_QUERIES = (
    "/api/v1/tenants/65a1b2c3d4e5f60718293a4b/benchmark-runs/65a1b2c3d4e5f60718293a4b/queries"
)
QUERY_LIST_BENCHMARK_QUERIES: dict[str, Any] = {}


async def test_list_benchmark_queries_success(client_factory: Any) -> None:
    fake = FakeService(QueriesService)
    client = client_factory({get_queries_service: fake})
    url = URL_LIST_BENCHMARK_QUERIES
    response = await client.request("GET", url, params=QUERY_LIST_BENCHMARK_QUERIES)
    assert response.status_code == 200, response.text
    ListBenchmarkQueriesResponse.model_validate(response.json())
    assert fake.calls and fake.calls[0][0] == "list_benchmark_queries"


@pytest.mark.parametrize(
    "error", [InvalidId(), BenchmarkRunNotFound()], ids=lambda e: type(e).__name__
)
async def test_list_benchmark_queries_declared_errors(client_factory: Any, error: Any) -> None:
    fake = FakeService(QueriesService, {"list_benchmark_queries": raising(error)})
    client = client_factory({get_queries_service: fake})
    url = URL_LIST_BENCHMARK_QUERIES
    response = await client.request("GET", url, params=QUERY_LIST_BENCHMARK_QUERIES)
    assert response.status_code == error.status_code, response.text
    assert response.json()["code"] == error.code
