"""Contract tests for `chunks` (G6): success, every declared error code, validation -> 400.

GENERATED by the backend coding agent - do not edit."""

from __future__ import annotations

from typing import Any

import pytest

from app.api.deps import get_chunks_service
from app.api.schemas import (
    GetDocumentChunksByProfileResponse,
    HybridSearchDocumentsRequest,
    HybridSearchDocumentsResponse,
    SearchAgentMemoryRequest,
    SearchAgentMemoryResponse,
    VectorSearchDocumentsRequest,
    VectorSearchDocumentsResponse,
)
from app.errors import (
    ChunkProfileNotFound,
    DocumentNotFound,
    EmbeddingGenerationFailed,
    ValidationError,
)
from app.services.chunks import ChunksService
from tests.support.factories import to_json_payload
from tests.support.fakes import FakeService, raising

URL_GET_DOCUMENT_CHUNKS_BY_PROFILE = (
    "/api/v1/tenants/65a1b2c3d4e5f60718293a4b/documents/65a1b2c3d4e5f60718293a4b/chunks"
)
QUERY_GET_DOCUMENT_CHUNKS_BY_PROFILE: dict[str, Any] = {
    "chunk_profile_id": "65a1b2c3d4e5f60718293a4b"
}


async def test_get_document_chunks_by_profile_success(client_factory: Any) -> None:
    fake = FakeService(ChunksService)
    client = client_factory({get_chunks_service: fake})
    url = URL_GET_DOCUMENT_CHUNKS_BY_PROFILE
    response = await client.request("GET", url, params=QUERY_GET_DOCUMENT_CHUNKS_BY_PROFILE)
    assert response.status_code == 200, response.text
    GetDocumentChunksByProfileResponse.model_validate(response.json())
    assert fake.calls and fake.calls[0][0] == "get_document_chunks_by_profile"


@pytest.mark.parametrize(
    "error", [ValidationError(), DocumentNotFound()], ids=lambda e: type(e).__name__
)
async def test_get_document_chunks_by_profile_declared_errors(
    client_factory: Any, error: Any
) -> None:
    fake = FakeService(ChunksService, {"get_document_chunks_by_profile": raising(error)})
    client = client_factory({get_chunks_service: fake})
    url = URL_GET_DOCUMENT_CHUNKS_BY_PROFILE
    response = await client.request("GET", url, params=QUERY_GET_DOCUMENT_CHUNKS_BY_PROFILE)
    assert response.status_code == error.status_code, response.text
    assert response.json()["code"] == error.code


async def test_get_document_chunks_by_profile_validation_chunk_profile_id_missing(
    client_factory: Any,
) -> None:
    fake = FakeService(ChunksService)
    client = client_factory({get_chunks_service: fake})
    url = URL_GET_DOCUMENT_CHUNKS_BY_PROFILE
    query = dict(QUERY_GET_DOCUMENT_CHUNKS_BY_PROFILE)
    query.pop("chunk_profile_id", None)
    response = await client.request("GET", url, params=query)
    assert response.status_code == 400, response.text
    assert response.json()["code"] == "VALIDATION_ERROR"
    assert not fake.calls


URL_VECTOR_SEARCH_DOCUMENTS = "/api/v1/tenants/65a1b2c3d4e5f60718293a4b/search/vector"
QUERY_VECTOR_SEARCH_DOCUMENTS: dict[str, Any] = {}


async def test_vector_search_documents_success(client_factory: Any) -> None:
    fake = FakeService(ChunksService)
    client = client_factory({get_chunks_service: fake})
    url = URL_VECTOR_SEARCH_DOCUMENTS
    response = await client.request(
        "POST",
        url,
        params=QUERY_VECTOR_SEARCH_DOCUMENTS,
        json=to_json_payload(VectorSearchDocumentsRequest),
    )
    assert response.status_code == 200, response.text
    VectorSearchDocumentsResponse.model_validate(response.json())
    assert fake.calls and fake.calls[0][0] == "vector_search_documents"


@pytest.mark.parametrize(
    "error",
    [ValidationError(), ChunkProfileNotFound(), EmbeddingGenerationFailed()],
    ids=lambda e: type(e).__name__,
)
async def test_vector_search_documents_declared_errors(client_factory: Any, error: Any) -> None:
    fake = FakeService(ChunksService, {"vector_search_documents": raising(error)})
    client = client_factory({get_chunks_service: fake})
    url = URL_VECTOR_SEARCH_DOCUMENTS
    response = await client.request(
        "POST",
        url,
        params=QUERY_VECTOR_SEARCH_DOCUMENTS,
        json=to_json_payload(VectorSearchDocumentsRequest),
    )
    assert response.status_code == error.status_code, response.text
    assert response.json()["code"] == error.code


async def test_vector_search_documents_validation_empty_body(client_factory: Any) -> None:
    fake = FakeService(ChunksService)
    client = client_factory({get_chunks_service: fake})
    url = URL_VECTOR_SEARCH_DOCUMENTS
    response = await client.request("POST", url, params=QUERY_VECTOR_SEARCH_DOCUMENTS, json={})
    assert response.status_code == 400, response.text
    assert response.json()["code"] in ["VALIDATION_ERROR"]
    assert not fake.calls


URL_HYBRID_SEARCH_DOCUMENTS = "/api/v1/tenants/65a1b2c3d4e5f60718293a4b/search/hybrid"
QUERY_HYBRID_SEARCH_DOCUMENTS: dict[str, Any] = {}


async def test_hybrid_search_documents_success(client_factory: Any) -> None:
    fake = FakeService(ChunksService)
    client = client_factory({get_chunks_service: fake})
    url = URL_HYBRID_SEARCH_DOCUMENTS
    response = await client.request(
        "POST",
        url,
        params=QUERY_HYBRID_SEARCH_DOCUMENTS,
        json=to_json_payload(HybridSearchDocumentsRequest),
    )
    assert response.status_code == 200, response.text
    HybridSearchDocumentsResponse.model_validate(response.json())
    assert fake.calls and fake.calls[0][0] == "hybrid_search_documents"


@pytest.mark.parametrize(
    "error", [ValidationError(), ChunkProfileNotFound()], ids=lambda e: type(e).__name__
)
async def test_hybrid_search_documents_declared_errors(client_factory: Any, error: Any) -> None:
    fake = FakeService(ChunksService, {"hybrid_search_documents": raising(error)})
    client = client_factory({get_chunks_service: fake})
    url = URL_HYBRID_SEARCH_DOCUMENTS
    response = await client.request(
        "POST",
        url,
        params=QUERY_HYBRID_SEARCH_DOCUMENTS,
        json=to_json_payload(HybridSearchDocumentsRequest),
    )
    assert response.status_code == error.status_code, response.text
    assert response.json()["code"] == error.code


async def test_hybrid_search_documents_validation_empty_body(client_factory: Any) -> None:
    fake = FakeService(ChunksService)
    client = client_factory({get_chunks_service: fake})
    url = URL_HYBRID_SEARCH_DOCUMENTS
    response = await client.request("POST", url, params=QUERY_HYBRID_SEARCH_DOCUMENTS, json={})
    assert response.status_code == 400, response.text
    assert response.json()["code"] in ["VALIDATION_ERROR"]
    assert not fake.calls


URL_SEARCH_AGENT_MEMORY = "/api/v1/tenants/65a1b2c3d4e5f60718293a4b/agent-memory/search"
QUERY_SEARCH_AGENT_MEMORY: dict[str, Any] = {}


async def test_search_agent_memory_success(client_factory: Any) -> None:
    fake = FakeService(ChunksService)
    client = client_factory({get_chunks_service: fake})
    url = URL_SEARCH_AGENT_MEMORY
    response = await client.request(
        "POST",
        url,
        params=QUERY_SEARCH_AGENT_MEMORY,
        json=to_json_payload(SearchAgentMemoryRequest),
    )
    assert response.status_code == 200, response.text
    SearchAgentMemoryResponse.model_validate(response.json())
    assert fake.calls and fake.calls[0][0] == "search_agent_memory"


@pytest.mark.parametrize(
    "error",
    [ValidationError(), ChunkProfileNotFound(), EmbeddingGenerationFailed()],
    ids=lambda e: type(e).__name__,
)
async def test_search_agent_memory_declared_errors(client_factory: Any, error: Any) -> None:
    fake = FakeService(ChunksService, {"search_agent_memory": raising(error)})
    client = client_factory({get_chunks_service: fake})
    url = URL_SEARCH_AGENT_MEMORY
    response = await client.request(
        "POST",
        url,
        params=QUERY_SEARCH_AGENT_MEMORY,
        json=to_json_payload(SearchAgentMemoryRequest),
    )
    assert response.status_code == error.status_code, response.text
    assert response.json()["code"] == error.code


async def test_search_agent_memory_validation_empty_body(client_factory: Any) -> None:
    fake = FakeService(ChunksService)
    client = client_factory({get_chunks_service: fake})
    url = URL_SEARCH_AGENT_MEMORY
    response = await client.request("POST", url, params=QUERY_SEARCH_AGENT_MEMORY, json={})
    assert response.status_code == 400, response.text
    assert response.json()["code"] in ["VALIDATION_ERROR"]
    assert not fake.calls
