"""Contract tests for `chunk_profiles` (G6): success, every declared error code, validation -> 400.

GENERATED by the backend coding agent - do not edit."""

from __future__ import annotations

from typing import Any

import pytest

from app.api.deps import get_chunk_profiles_service
from app.api.schemas import (
    CreateChunkProfileRequest,
    CreateChunkProfileResponse,
    ListChunkProfilesResponse,
)
from app.errors import InvalidId, TenantNotFound, ValidationError
from app.services.chunk_profiles import ChunkProfilesService
from tests.support.factories import to_json_payload
from tests.support.fakes import FakeService, raising

URL_LIST_CHUNK_PROFILES = "/api/v1/tenants/65a1b2c3d4e5f60718293a4b/chunk-profiles"
QUERY_LIST_CHUNK_PROFILES: dict[str, Any] = {}


async def test_list_chunk_profiles_success(client_factory: Any) -> None:
    fake = FakeService(ChunkProfilesService)
    client = client_factory({get_chunk_profiles_service: fake})
    url = URL_LIST_CHUNK_PROFILES
    response = await client.request("GET", url, params=QUERY_LIST_CHUNK_PROFILES)
    assert response.status_code == 200, response.text
    ListChunkProfilesResponse.model_validate(response.json())
    assert fake.calls and fake.calls[0][0] == "list_chunk_profiles"


@pytest.mark.parametrize("error", [InvalidId()], ids=lambda e: type(e).__name__)
async def test_list_chunk_profiles_declared_errors(client_factory: Any, error: Any) -> None:
    fake = FakeService(ChunkProfilesService, {"list_chunk_profiles": raising(error)})
    client = client_factory({get_chunk_profiles_service: fake})
    url = URL_LIST_CHUNK_PROFILES
    response = await client.request("GET", url, params=QUERY_LIST_CHUNK_PROFILES)
    assert response.status_code == error.status_code, response.text
    assert response.json()["code"] == error.code


URL_CREATE_CHUNK_PROFILE = "/api/v1/tenants/65a1b2c3d4e5f60718293a4b/chunk-profiles"
QUERY_CREATE_CHUNK_PROFILE: dict[str, Any] = {}


async def test_create_chunk_profile_success(client_factory: Any) -> None:
    fake = FakeService(ChunkProfilesService)
    client = client_factory({get_chunk_profiles_service: fake})
    url = URL_CREATE_CHUNK_PROFILE
    response = await client.request(
        "POST",
        url,
        params=QUERY_CREATE_CHUNK_PROFILE,
        json=to_json_payload(CreateChunkProfileRequest),
    )
    assert response.status_code == 201, response.text
    CreateChunkProfileResponse.model_validate(response.json())
    assert fake.calls and fake.calls[0][0] == "create_chunk_profile"


@pytest.mark.parametrize(
    "error", [ValidationError(), TenantNotFound()], ids=lambda e: type(e).__name__
)
async def test_create_chunk_profile_declared_errors(client_factory: Any, error: Any) -> None:
    fake = FakeService(ChunkProfilesService, {"create_chunk_profile": raising(error)})
    client = client_factory({get_chunk_profiles_service: fake})
    url = URL_CREATE_CHUNK_PROFILE
    response = await client.request(
        "POST",
        url,
        params=QUERY_CREATE_CHUNK_PROFILE,
        json=to_json_payload(CreateChunkProfileRequest),
    )
    assert response.status_code == error.status_code, response.text
    assert response.json()["code"] == error.code


async def test_create_chunk_profile_validation_empty_body(client_factory: Any) -> None:
    fake = FakeService(ChunkProfilesService)
    client = client_factory({get_chunk_profiles_service: fake})
    url = URL_CREATE_CHUNK_PROFILE
    response = await client.request("POST", url, params=QUERY_CREATE_CHUNK_PROFILE, json={})
    assert response.status_code == 400, response.text
    assert response.json()["code"] in ["VALIDATION_ERROR"]
    assert not fake.calls
