"""Contract tests for `documents` (G6): success, every declared error code, validation -> 400.

GENERATED by the backend coding agent - do not edit."""

from __future__ import annotations

from typing import Any

import pytest

from app.api.deps import get_documents_service
from app.api.schemas import (
    CreateDocumentRequest,
    CreateDocumentResponse,
    GetDocumentResponse,
    ListDocumentIngestStatusesResponse,
    ListRetrievalReadyDocumentsResponse,
    UpdateDocumentRequest,
    UpdateDocumentResponse,
)
from app.errors import DocumentNotFound, InvalidId, TenantNotFound, ValidationError
from app.services.documents import DocumentsService
from tests.support.factories import to_json_payload
from tests.support.fakes import FakeService, raising

URL_CREATE_DOCUMENT = "/api/v1/tenants/65a1b2c3d4e5f60718293a4b/documents"
QUERY_CREATE_DOCUMENT: dict[str, Any] = {}


async def test_create_document_success(client_factory: Any) -> None:
    fake = FakeService(DocumentsService)
    client = client_factory({get_documents_service: fake})
    url = URL_CREATE_DOCUMENT
    response = await client.request(
        "POST", url, params=QUERY_CREATE_DOCUMENT, json=to_json_payload(CreateDocumentRequest)
    )
    assert response.status_code == 201, response.text
    CreateDocumentResponse.model_validate(response.json())
    assert fake.calls and fake.calls[0][0] == "create_document"


@pytest.mark.parametrize(
    "error", [ValidationError(), TenantNotFound()], ids=lambda e: type(e).__name__
)
async def test_create_document_declared_errors(client_factory: Any, error: Any) -> None:
    fake = FakeService(DocumentsService, {"create_document": raising(error)})
    client = client_factory({get_documents_service: fake})
    url = URL_CREATE_DOCUMENT
    response = await client.request(
        "POST", url, params=QUERY_CREATE_DOCUMENT, json=to_json_payload(CreateDocumentRequest)
    )
    assert response.status_code == error.status_code, response.text
    assert response.json()["code"] == error.code


async def test_create_document_validation_empty_body(client_factory: Any) -> None:
    fake = FakeService(DocumentsService)
    client = client_factory({get_documents_service: fake})
    url = URL_CREATE_DOCUMENT
    response = await client.request("POST", url, params=QUERY_CREATE_DOCUMENT, json={})
    assert response.status_code == 400, response.text
    assert response.json()["code"] in ["VALIDATION_ERROR"]
    assert not fake.calls


URL_LIST_RETRIEVAL_READY_DOCUMENTS = "/api/v1/tenants/65a1b2c3d4e5f60718293a4b/documents"
QUERY_LIST_RETRIEVAL_READY_DOCUMENTS: dict[str, Any] = {"created_after": "2026-01-01T00:00:00Z"}


async def test_list_retrieval_ready_documents_success(client_factory: Any) -> None:
    fake = FakeService(DocumentsService)
    client = client_factory({get_documents_service: fake})
    url = URL_LIST_RETRIEVAL_READY_DOCUMENTS
    response = await client.request("GET", url, params=QUERY_LIST_RETRIEVAL_READY_DOCUMENTS)
    assert response.status_code == 200, response.text
    ListRetrievalReadyDocumentsResponse.model_validate(response.json())
    assert fake.calls and fake.calls[0][0] == "list_retrieval_ready_documents"


@pytest.mark.parametrize(
    "error", [ValidationError(), TenantNotFound()], ids=lambda e: type(e).__name__
)
async def test_list_retrieval_ready_documents_declared_errors(
    client_factory: Any, error: Any
) -> None:
    fake = FakeService(DocumentsService, {"list_retrieval_ready_documents": raising(error)})
    client = client_factory({get_documents_service: fake})
    url = URL_LIST_RETRIEVAL_READY_DOCUMENTS
    response = await client.request("GET", url, params=QUERY_LIST_RETRIEVAL_READY_DOCUMENTS)
    assert response.status_code == error.status_code, response.text
    assert response.json()["code"] == error.code


async def test_list_retrieval_ready_documents_validation_ready_only_not_boolean(
    client_factory: Any,
) -> None:
    fake = FakeService(DocumentsService)
    client = client_factory({get_documents_service: fake})
    url = URL_LIST_RETRIEVAL_READY_DOCUMENTS
    query = dict(QUERY_LIST_RETRIEVAL_READY_DOCUMENTS)
    query["ready_only"] = "maybe"
    response = await client.request("GET", url, params=query)
    assert response.status_code == 400, response.text
    assert response.json()["code"] == "VALIDATION_ERROR"
    assert not fake.calls


async def test_list_retrieval_ready_documents_validation_created_after_malformed(
    client_factory: Any,
) -> None:
    fake = FakeService(DocumentsService)
    client = client_factory({get_documents_service: fake})
    url = URL_LIST_RETRIEVAL_READY_DOCUMENTS
    query = dict(QUERY_LIST_RETRIEVAL_READY_DOCUMENTS)
    query["created_after"] = "not-a-date"
    response = await client.request("GET", url, params=query)
    assert response.status_code == 400, response.text
    assert response.json()["code"] == "VALIDATION_ERROR"
    assert not fake.calls


async def test_list_retrieval_ready_documents_validation_limit_not_numeric(
    client_factory: Any,
) -> None:
    fake = FakeService(DocumentsService)
    client = client_factory({get_documents_service: fake})
    url = URL_LIST_RETRIEVAL_READY_DOCUMENTS
    query = dict(QUERY_LIST_RETRIEVAL_READY_DOCUMENTS)
    query["limit"] = "abc"
    response = await client.request("GET", url, params=query)
    assert response.status_code == 400, response.text
    assert response.json()["code"] == "VALIDATION_ERROR"
    assert not fake.calls


URL_LIST_DOCUMENT_INGEST_STATUSES = (
    "/api/v1/tenants/65a1b2c3d4e5f60718293a4b/documents/ingest-status"
)
QUERY_LIST_DOCUMENT_INGEST_STATUSES: dict[str, Any] = {"created_after": "2026-01-01T00:00:00Z"}


async def test_list_document_ingest_statuses_success(client_factory: Any) -> None:
    fake = FakeService(DocumentsService)
    client = client_factory({get_documents_service: fake})
    url = URL_LIST_DOCUMENT_INGEST_STATUSES
    response = await client.request("GET", url, params=QUERY_LIST_DOCUMENT_INGEST_STATUSES)
    assert response.status_code == 200, response.text
    ListDocumentIngestStatusesResponse.model_validate(response.json())
    assert fake.calls and fake.calls[0][0] == "list_document_ingest_statuses"


@pytest.mark.parametrize(
    "error", [ValidationError(), TenantNotFound()], ids=lambda e: type(e).__name__
)
async def test_list_document_ingest_statuses_declared_errors(
    client_factory: Any, error: Any
) -> None:
    fake = FakeService(DocumentsService, {"list_document_ingest_statuses": raising(error)})
    client = client_factory({get_documents_service: fake})
    url = URL_LIST_DOCUMENT_INGEST_STATUSES
    response = await client.request("GET", url, params=QUERY_LIST_DOCUMENT_INGEST_STATUSES)
    assert response.status_code == error.status_code, response.text
    assert response.json()["code"] == error.code


async def test_list_document_ingest_statuses_validation_created_after_malformed(
    client_factory: Any,
) -> None:
    fake = FakeService(DocumentsService)
    client = client_factory({get_documents_service: fake})
    url = URL_LIST_DOCUMENT_INGEST_STATUSES
    query = dict(QUERY_LIST_DOCUMENT_INGEST_STATUSES)
    query["created_after"] = "not-a-date"
    response = await client.request("GET", url, params=query)
    assert response.status_code == 400, response.text
    assert response.json()["code"] == "VALIDATION_ERROR"
    assert not fake.calls


async def test_list_document_ingest_statuses_validation_limit_not_numeric(
    client_factory: Any,
) -> None:
    fake = FakeService(DocumentsService)
    client = client_factory({get_documents_service: fake})
    url = URL_LIST_DOCUMENT_INGEST_STATUSES
    query = dict(QUERY_LIST_DOCUMENT_INGEST_STATUSES)
    query["limit"] = "abc"
    response = await client.request("GET", url, params=query)
    assert response.status_code == 400, response.text
    assert response.json()["code"] == "VALIDATION_ERROR"
    assert not fake.calls


URL_GET_DOCUMENT = "/api/v1/tenants/65a1b2c3d4e5f60718293a4b/documents/65a1b2c3d4e5f60718293a4b"
QUERY_GET_DOCUMENT: dict[str, Any] = {}


async def test_get_document_success(client_factory: Any) -> None:
    fake = FakeService(DocumentsService)
    client = client_factory({get_documents_service: fake})
    url = URL_GET_DOCUMENT
    response = await client.request("GET", url, params=QUERY_GET_DOCUMENT)
    assert response.status_code == 200, response.text
    GetDocumentResponse.model_validate(response.json())
    assert fake.calls and fake.calls[0][0] == "get_document"


@pytest.mark.parametrize("error", [InvalidId(), DocumentNotFound()], ids=lambda e: type(e).__name__)
async def test_get_document_declared_errors(client_factory: Any, error: Any) -> None:
    fake = FakeService(DocumentsService, {"get_document": raising(error)})
    client = client_factory({get_documents_service: fake})
    url = URL_GET_DOCUMENT
    response = await client.request("GET", url, params=QUERY_GET_DOCUMENT)
    assert response.status_code == error.status_code, response.text
    assert response.json()["code"] == error.code


URL_UPDATE_DOCUMENT = "/api/v1/tenants/65a1b2c3d4e5f60718293a4b/documents/65a1b2c3d4e5f60718293a4b"
QUERY_UPDATE_DOCUMENT: dict[str, Any] = {}


async def test_update_document_success(client_factory: Any) -> None:
    fake = FakeService(DocumentsService)
    client = client_factory({get_documents_service: fake})
    url = URL_UPDATE_DOCUMENT
    response = await client.request(
        "PATCH", url, params=QUERY_UPDATE_DOCUMENT, json=to_json_payload(UpdateDocumentRequest)
    )
    assert response.status_code == 200, response.text
    UpdateDocumentResponse.model_validate(response.json())
    assert fake.calls and fake.calls[0][0] == "update_document"


@pytest.mark.parametrize(
    "error", [ValidationError(), DocumentNotFound()], ids=lambda e: type(e).__name__
)
async def test_update_document_declared_errors(client_factory: Any, error: Any) -> None:
    fake = FakeService(DocumentsService, {"update_document": raising(error)})
    client = client_factory({get_documents_service: fake})
    url = URL_UPDATE_DOCUMENT
    response = await client.request(
        "PATCH", url, params=QUERY_UPDATE_DOCUMENT, json=to_json_payload(UpdateDocumentRequest)
    )
    assert response.status_code == error.status_code, response.text
    assert response.json()["code"] == error.code
