"""Contract tests for `tenants` (G6): success, every declared error code, validation -> 400.

GENERATED by the backend coding agent - do not edit."""

from __future__ import annotations

from typing import Any

import pytest

from app.api.deps import get_tenants_service
from app.api.schemas import (
    CreateTenantRequest,
    CreateTenantResponse,
    GetTenantResponse,
    ListTenantsResponse,
    UpdateTenantRequest,
    UpdateTenantResponse,
)
from app.errors import (
    InvalidId,
    TenantKeyConflict,
    TenantKeyImmutable,
    TenantNotFound,
    ValidationError,
)
from app.services.tenants import TenantsService
from tests.support.factories import to_json_payload
from tests.support.fakes import FakeService, raising

URL_CREATE_TENANT = "/api/v1/tenants"
QUERY_CREATE_TENANT: dict[str, Any] = {}


async def test_create_tenant_success(client_factory: Any) -> None:
    fake = FakeService(TenantsService)
    client = client_factory({get_tenants_service: fake})
    url = URL_CREATE_TENANT
    response = await client.request(
        "POST", url, params=QUERY_CREATE_TENANT, json=to_json_payload(CreateTenantRequest)
    )
    assert response.status_code == 201, response.text
    CreateTenantResponse.model_validate(response.json())
    assert fake.calls and fake.calls[0][0] == "create_tenant"


@pytest.mark.parametrize(
    "error", [ValidationError(), TenantKeyConflict()], ids=lambda e: type(e).__name__
)
async def test_create_tenant_declared_errors(client_factory: Any, error: Any) -> None:
    fake = FakeService(TenantsService, {"create_tenant": raising(error)})
    client = client_factory({get_tenants_service: fake})
    url = URL_CREATE_TENANT
    response = await client.request(
        "POST", url, params=QUERY_CREATE_TENANT, json=to_json_payload(CreateTenantRequest)
    )
    assert response.status_code == error.status_code, response.text
    assert response.json()["code"] == error.code


async def test_create_tenant_validation_empty_body(client_factory: Any) -> None:
    fake = FakeService(TenantsService)
    client = client_factory({get_tenants_service: fake})
    url = URL_CREATE_TENANT
    response = await client.request("POST", url, params=QUERY_CREATE_TENANT, json={})
    assert response.status_code == 400, response.text
    assert response.json()["code"] in ["VALIDATION_ERROR"]
    assert not fake.calls


URL_LIST_TENANTS = "/api/v1/tenants"
QUERY_LIST_TENANTS: dict[str, Any] = {"status": "active"}


async def test_list_tenants_success(client_factory: Any) -> None:
    fake = FakeService(TenantsService)
    client = client_factory({get_tenants_service: fake})
    url = URL_LIST_TENANTS
    response = await client.request("GET", url, params=QUERY_LIST_TENANTS)
    assert response.status_code == 200, response.text
    ListTenantsResponse.model_validate(response.json())
    assert fake.calls and fake.calls[0][0] == "list_tenants"


@pytest.mark.parametrize("error", [ValidationError()], ids=lambda e: type(e).__name__)
async def test_list_tenants_declared_errors(client_factory: Any, error: Any) -> None:
    fake = FakeService(TenantsService, {"list_tenants": raising(error)})
    client = client_factory({get_tenants_service: fake})
    url = URL_LIST_TENANTS
    response = await client.request("GET", url, params=QUERY_LIST_TENANTS)
    assert response.status_code == error.status_code, response.text
    assert response.json()["code"] == error.code


async def test_list_tenants_validation_status_not_allowed(client_factory: Any) -> None:
    fake = FakeService(TenantsService)
    client = client_factory({get_tenants_service: fake})
    url = URL_LIST_TENANTS
    query = dict(QUERY_LIST_TENANTS)
    query["status"] = "__invalid__"
    response = await client.request("GET", url, params=query)
    assert response.status_code == 400, response.text
    assert response.json()["code"] == "VALIDATION_ERROR"
    assert not fake.calls


async def test_list_tenants_validation_limit_not_numeric(client_factory: Any) -> None:
    fake = FakeService(TenantsService)
    client = client_factory({get_tenants_service: fake})
    url = URL_LIST_TENANTS
    query = dict(QUERY_LIST_TENANTS)
    query["limit"] = "abc"
    response = await client.request("GET", url, params=query)
    assert response.status_code == 400, response.text
    assert response.json()["code"] == "VALIDATION_ERROR"
    assert not fake.calls


URL_GET_TENANT = "/api/v1/tenants/65a1b2c3d4e5f60718293a4b"
QUERY_GET_TENANT: dict[str, Any] = {}


async def test_get_tenant_success(client_factory: Any) -> None:
    fake = FakeService(TenantsService)
    client = client_factory({get_tenants_service: fake})
    url = URL_GET_TENANT
    response = await client.request("GET", url, params=QUERY_GET_TENANT)
    assert response.status_code == 200, response.text
    GetTenantResponse.model_validate(response.json())
    assert fake.calls and fake.calls[0][0] == "get_tenant"


@pytest.mark.parametrize("error", [InvalidId(), TenantNotFound()], ids=lambda e: type(e).__name__)
async def test_get_tenant_declared_errors(client_factory: Any, error: Any) -> None:
    fake = FakeService(TenantsService, {"get_tenant": raising(error)})
    client = client_factory({get_tenants_service: fake})
    url = URL_GET_TENANT
    response = await client.request("GET", url, params=QUERY_GET_TENANT)
    assert response.status_code == error.status_code, response.text
    assert response.json()["code"] == error.code


URL_UPDATE_TENANT = "/api/v1/tenants/65a1b2c3d4e5f60718293a4b"
QUERY_UPDATE_TENANT: dict[str, Any] = {}


async def test_update_tenant_success(client_factory: Any) -> None:
    fake = FakeService(TenantsService)
    client = client_factory({get_tenants_service: fake})
    url = URL_UPDATE_TENANT
    response = await client.request(
        "PATCH", url, params=QUERY_UPDATE_TENANT, json=to_json_payload(UpdateTenantRequest)
    )
    assert response.status_code == 200, response.text
    UpdateTenantResponse.model_validate(response.json())
    assert fake.calls and fake.calls[0][0] == "update_tenant"


@pytest.mark.parametrize(
    "error",
    [ValidationError(), TenantNotFound(), TenantKeyImmutable()],
    ids=lambda e: type(e).__name__,
)
async def test_update_tenant_declared_errors(client_factory: Any, error: Any) -> None:
    fake = FakeService(TenantsService, {"update_tenant": raising(error)})
    client = client_factory({get_tenants_service: fake})
    url = URL_UPDATE_TENANT
    response = await client.request(
        "PATCH", url, params=QUERY_UPDATE_TENANT, json=to_json_payload(UpdateTenantRequest)
    )
    assert response.status_code == error.status_code, response.text
    assert response.json()["code"] == error.code
