"""Repository container injected into services.

GENERATED by the backend coding agent - do not edit (read-only, verified by G8)."""

from __future__ import annotations

from pymongo.asynchronous.database import AsyncDatabase

from app.db.base import Document
from app.db.repositories.benchmark_runs import BenchmarkRunsRepository
from app.db.repositories.chunk_profiles import ChunkProfilesRepository
from app.db.repositories.chunks import ChunksRepository
from app.db.repositories.documents import DocumentsRepository
from app.db.repositories.queries import QueriesRepository
from app.db.repositories.query_results import QueryResultsRepository
from app.db.repositories.tenants import TenantsRepository


class Repositories:
    """One repository per collection. Services receive this via dependency injection."""

    def __init__(self, db: AsyncDatabase[Document]) -> None:
        self.tenants = TenantsRepository(db["tenants"])
        self.documents = DocumentsRepository(db["documents"])
        self.chunk_profiles = ChunkProfilesRepository(db["chunk_profiles"])
        self.chunks = ChunksRepository(db["chunks"])
        self.queries = QueriesRepository(db["queries"])
        self.benchmark_runs = BenchmarkRunsRepository(db["benchmark_runs"])
        self.query_results = QueryResultsRepository(db["query_results"])


__all__ = [
    "BenchmarkRunsRepository",
    "ChunkProfilesRepository",
    "ChunksRepository",
    "DocumentsRepository",
    "QueriesRepository",
    "QueryResultsRepository",
    "Repositories",
    "TenantsRepository",
]
