"""Repository for `chunks`.

GENERATED by the backend coding agent - do not edit (read-only, verified by G8)."""

from __future__ import annotations

from typing import Any

from app.db import queries
from app.db.base import (
    BaseRepository,
    Document,
    QueryRow,
    convert_object_ids,
    to_object_id,
    validate_document,
)
from app.models.documents import ChunksDocument


class ChunksRepository(BaseRepository):
    """Typed access to `chunks`. Services use these methods; never the driver."""

    collection_name = "chunks"

    OBJECT_ID_PATHS: tuple[str, ...] = ("tenant_id", "document_id", "chunk_profile_id")

    @classmethod
    def _to_mongo(cls, raw: dict[str, Any]) -> Document:
        """Convert ObjectId-typed fields (kept as hex strings in models) back to ObjectId."""
        return convert_object_ids(raw, cls.OBJECT_ID_PATHS)

    async def find_one_by_id(self, value: str) -> ChunksDocument | None:
        """Find one `chunks` document by _id (primary key)."""
        raw = await self.collection.find_one({"_id": to_object_id(value)})
        return None if raw is None else validate_document(ChunksDocument, raw, self.collection_name)

    async def run_qp_4(
        self,
        *,
        query_embedding: list[float],
        num_candidates: int,
        top_k: int,
        tenant_id: str,
        chunk_profile_id: str,
        document_ids: list[str] | None = None,
        user_id: str | None = None,
        group_ids: list[str] | None = None,
    ) -> list[QueryRow]:
        """QP-4 - Vector retrieve chunks for document search. Rows are the pattern's projection; validate them into response models."""
        return await self._aggregate(
            queries.qp_4(
                query_embedding=query_embedding,
                num_candidates=num_candidates,
                top_k=top_k,
                tenant_id=to_object_id(tenant_id),
                chunk_profile_id=to_object_id(chunk_profile_id),
                document_ids=None
                if document_ids is None
                else [to_object_id(item) for item in document_ids],
                user_id=None if user_id is None else to_object_id(user_id),
                group_ids=None if group_ids is None else [to_object_id(item) for item in group_ids],
            )
        )

    async def run_qp_5(
        self,
        *,
        query_text: str,
        tenant_id: str,
        chunk_profile_id: str,
        top_k: int,
        metadata_filters: dict[str, Any] | list[dict[str, Any]] | None = None,
        document_scope_filters: dict[str, Any] | list[dict[str, Any]] | None = None,
    ) -> list[QueryRow]:
        """QP-5 - Hybrid lexical plus metadata retrieval over chunks. Rows are the pattern's projection; validate them into response models."""
        return await self._aggregate(
            queries.qp_5(
                query_text=query_text,
                tenant_id=to_object_id(tenant_id),
                chunk_profile_id=to_object_id(chunk_profile_id),
                metadata_filters=metadata_filters,
                document_scope_filters=document_scope_filters,
                top_k=top_k,
            )
        )

    async def run_qp_6(
        self,
        *,
        query_embedding: list[float],
        num_candidates: int,
        top_k: int,
        tenant_id: str,
        chunk_profile_id: str,
        user_id: str,
        group_ids: list[str],
        memory_type: str | None = None,
    ) -> list[QueryRow]:
        """QP-6 - Agent memory retrieval for a tenant. Rows are the pattern's projection; validate them into response models."""
        return await self._aggregate(
            queries.qp_6(
                query_embedding=query_embedding,
                num_candidates=num_candidates,
                top_k=top_k,
                tenant_id=to_object_id(tenant_id),
                chunk_profile_id=to_object_id(chunk_profile_id),
                memory_type=memory_type,
                user_id=to_object_id(user_id),
                group_ids=[to_object_id(item) for item in group_ids],
            )
        )

    async def run_qp_7(self, *, document_id: str, chunk_profile_id: str) -> list[QueryRow]:
        """QP-7 - Get ordered chunks for a document under a specific chunking strategy. Rows are the pattern's projection; validate them into response models."""
        return await self._aggregate(
            queries.qp_7(
                document_id=to_object_id(document_id),
                chunk_profile_id=to_object_id(chunk_profile_id),
            )
        )
