"""Repository for `documents`.

GENERATED by the backend coding agent - do not edit (read-only, verified by G8)."""

from __future__ import annotations

from datetime import datetime
from typing import Any

from app.db import queries
from app.db.base import (
    MAX_FIND_RESULTS,
    BaseRepository,
    Document,
    QueryRow,
    convert_object_ids,
    to_object_id,
    validate_document,
)
from app.models.documents import DocumentsDocument


class DocumentsRepository(BaseRepository):
    """Typed access to `documents`. Services use these methods; never the driver."""

    collection_name = "documents"

    OBJECT_ID_PATHS: tuple[str, ...] = ("tenant_id", "access.user_ids[]", "access.group_ids[]")

    @classmethod
    def _to_mongo(cls, raw: dict[str, Any]) -> Document:
        """Convert ObjectId-typed fields (kept as hex strings in models) back to ObjectId."""
        return convert_object_ids(raw, cls.OBJECT_ID_PATHS)

    async def find_one_by_id(self, value: str) -> DocumentsDocument | None:
        """Find one `documents` document by _id (primary key)."""
        raw = await self.collection.find_one({"_id": to_object_id(value)})
        return (
            None if raw is None else validate_document(DocumentsDocument, raw, self.collection_name)
        )

    async def insert_one(self, document: DocumentsDocument) -> None:
        """Insert one `documents` document (used by createDocument). Raises DuplicateKeyConflict on unique-index violation."""
        raw = document.model_dump(by_alias=True, exclude_none=True)
        await self._insert(self._to_mongo(raw))

    async def find_many(
        self, *, tenant_id: str | None = None, limit: int = MAX_FIND_RESULTS
    ) -> list[DocumentsDocument]:
        """Find `documents` documents with optional equality filters (used by listRetrievalReadyDocuments); capped at `limit`."""
        filter_: dict[str, Any] = {}
        if tenant_id is not None:
            filter_["tenant_id"] = to_object_id(tenant_id)
        rows = await self._find(filter_, limit=limit)
        return [validate_document(DocumentsDocument, row, self.collection_name) for row in rows]

    async def find_one_by_id_and_tenant_id(
        self, *, id: str, tenant_id: str
    ) -> DocumentsDocument | None:
        """Find one `documents` document by _id, tenant_id (used by getDocument)."""
        raw = await self.collection.find_one(
            {"_id": to_object_id(id), "tenant_id": to_object_id(tenant_id)}
        )
        return (
            None if raw is None else validate_document(DocumentsDocument, raw, self.collection_name)
        )

    async def update_one_by_id_and_tenant_id(
        self, *, id: str, tenant_id: str, changes: dict[str, Any]
    ) -> bool:
        """Set `changes` (field -> value) on one `documents` document (used by updateDocument). Returns False when nothing matched."""
        result = await self.collection.update_one(
            {"_id": to_object_id(id), "tenant_id": to_object_id(tenant_id)},
            {"$set": self._to_mongo(changes)},
        )
        return result.matched_count > 0

    async def run_qp_1(
        self, *, tenant_id: str, page_size: int, start_date: datetime | None = None
    ) -> list[QueryRow]:
        """QP-1 - List retrieval-ready documents for a tenant demo session. Rows are the pattern's projection; validate them into response models."""
        query = queries.qp_1(
            tenant_id=to_object_id(tenant_id), start_date=start_date, page_size=page_size
        )
        sort = list(query["sort"].items()) if query["sort"] else None
        return await self._find(
            query["filter"], query["projection"], sort, query["limit"] or MAX_FIND_RESULTS
        )

    async def run_qp_2(
        self, *, tenant_id: str, page_size: int, start_date: datetime | None = None
    ) -> list[QueryRow]:
        """QP-2 - Inspect document ingest pipeline status and failures. Rows are the pattern's projection; validate them into response models."""
        query = queries.qp_2(
            tenant_id=to_object_id(tenant_id), start_date=start_date, page_size=page_size
        )
        sort = list(query["sort"].items()) if query["sort"] else None
        return await self._find(
            query["filter"], query["projection"], sort, query["limit"] or MAX_FIND_RESULTS
        )
