"""Repository for `queries`.

GENERATED by the backend coding agent - do not edit (read-only, verified by G8)."""

from __future__ import annotations

from datetime import datetime
from typing import Any

from app.db import queries
from app.db.base import (
    MAX_FIND_RESULTS,
    BaseRepository,
    Document,
    QueryRow,
    convert_object_ids,
    to_object_id,
    validate_document,
)
from app.models.documents import QueriesDocument


class QueriesRepository(BaseRepository):
    """Typed access to `queries`. Services use these methods; never the driver."""

    collection_name = "queries"

    OBJECT_ID_PATHS: tuple[str, ...] = (
        "tenant_id",
        "benchmark_run_id",
        "ground_truth_chunk_ids[]",
        "ground_truth_document_ids[]",
        "document_scope.document_ids[]",
    )

    @classmethod
    def _to_mongo(cls, raw: dict[str, Any]) -> Document:
        """Convert ObjectId-typed fields (kept as hex strings in models) back to ObjectId."""
        return convert_object_ids(raw, cls.OBJECT_ID_PATHS)

    async def find_one_by_id(self, value: str) -> QueriesDocument | None:
        """Find one `queries` document by _id (primary key)."""
        raw = await self.collection.find_one({"_id": to_object_id(value)})
        return (
            None if raw is None else validate_document(QueriesDocument, raw, self.collection_name)
        )

    async def insert_one(self, document: QueriesDocument) -> None:
        """Insert one `queries` document (used by createQuery). Raises DuplicateKeyConflict on unique-index violation."""
        raw = document.model_dump(by_alias=True, exclude_none=True)
        await self._insert(self._to_mongo(raw))

    async def run_qp_9(self, *, tenant_id: str, benchmark_run_id: str) -> list[QueryRow]:
        """QP-9 - List queries for a benchmark run. Rows are the pattern's projection; validate them into response models."""
        query = queries.qp_9(
            tenant_id=to_object_id(tenant_id), benchmark_run_id=to_object_id(benchmark_run_id)
        )
        sort = list(query["sort"].items()) if query["sort"] else None
        return await self._find(
            query["filter"], query["projection"], sort, query["limit"] or MAX_FIND_RESULTS
        )

    async def run_qp_13(
        self, *, tenant_id: str, page_size: int, start_date: datetime | None = None
    ) -> list[QueryRow]:
        """QP-13 - Recent ad hoc query history for a tenant. Rows are the pattern's projection; validate them into response models."""
        query = queries.qp_13(
            tenant_id=to_object_id(tenant_id), start_date=start_date, page_size=page_size
        )
        sort = list(query["sort"].items()) if query["sort"] else None
        return await self._find(
            query["filter"], query["projection"], sort, query["limit"] or MAX_FIND_RESULTS
        )
