"""Repository for `tenants`.

GENERATED by the backend coding agent - do not edit (read-only, verified by G8)."""

from __future__ import annotations

from typing import Any, Literal

from app.db.base import (
    MAX_FIND_RESULTS,
    BaseRepository,
    Document,
    convert_object_ids,
    to_object_id,
    validate_document,
)
from app.models.documents import TenantsDocument


class TenantsRepository(BaseRepository):
    """Typed access to `tenants`. Services use these methods; never the driver."""

    collection_name = "tenants"

    OBJECT_ID_PATHS: tuple[str, ...] = ()

    @classmethod
    def _to_mongo(cls, raw: dict[str, Any]) -> Document:
        """Convert ObjectId-typed fields (kept as hex strings in models) back to ObjectId."""
        return convert_object_ids(raw, cls.OBJECT_ID_PATHS)

    async def find_one_by_id(self, value: str) -> TenantsDocument | None:
        """Find one `tenants` document by _id (primary key)."""
        raw = await self.collection.find_one({"_id": to_object_id(value)})
        return (
            None if raw is None else validate_document(TenantsDocument, raw, self.collection_name)
        )

    async def find_one_by_tenant_key(self, value: str) -> TenantsDocument | None:
        """Find one `tenants` document by tenant_key (unique index uk_tenant_key)."""
        raw = await self.collection.find_one({"tenant_key": value})
        return (
            None if raw is None else validate_document(TenantsDocument, raw, self.collection_name)
        )

    async def insert_one(self, document: TenantsDocument) -> None:
        """Insert one `tenants` document (used by createTenant). Raises DuplicateKeyConflict on unique-index violation."""
        raw = document.model_dump(by_alias=True, exclude_none=True)
        await self._insert(self._to_mongo(raw))

    async def find_many(
        self, *, status: Literal["active", "inactive"] | None = None, limit: int = MAX_FIND_RESULTS
    ) -> list[TenantsDocument]:
        """Find `tenants` documents with optional equality filters (used by listTenants); capped at `limit`."""
        filter_: dict[str, Any] = {}
        if status is not None:
            filter_["status"] = status
        rows = await self._find(filter_, limit=limit)
        return [validate_document(TenantsDocument, row, self.collection_name) for row in rows]

    async def update_one_by_id(self, value: str, changes: dict[str, Any]) -> bool:
        """Set `changes` (field -> value) on one `tenants` document (used by updateTenant). Returns False when nothing matched."""
        result = await self.collection.update_one(
            {"_id": to_object_id(value)}, {"$set": self._to_mongo(changes)}
        )
        return result.matched_count > 0
