"""Pydantic models for stored documents (from data_model).

GENERATED by the backend coding agent - do not edit (read-only, verified by G8)."""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel, ConfigDict, Field

from app.types import AnyJson, PyObjectId, UtcDatetime


class TenantsDocument(BaseModel):
    """Document in `tenants`. Tenant/customer isolation boundary for uploaded documents, agent memory, benchmark runs, and queries. Included because Tenant is an explicit business entity and retrieval/evaluation flows are tenant-scoped."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: PyObjectId | None = Field(default=None, alias="_id")
    tenant_key: str
    name: str
    deployment_model: Literal["shared", "isolated"] | None = None
    cloud: Literal["aws", "gcp", "azure", "other"] | None = None
    status: Literal["active", "inactive"]
    created_at: UtcDatetime
    updated_at: UtcDatetime


class DocumentsDocumentAccess(BaseModel):
    """Embedded `access`."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    user_ids: list[PyObjectId] | None = None
    group_ids: list[PyObjectId] | None = None


class DocumentsDocument(BaseModel):
    """Document in `documents`. Top-level customer-provided content and conversation-derived memory documents used for retrieval. Stores source metadata and extracted text, while raw binary may remain external (e.g. S3) per current-state integration context."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: PyObjectId | None = Field(default=None, alias="_id")
    tenant_id: PyObjectId
    document_type: Literal[
        "pdf",
        "csv",
        "google_sheet",
        "text",
        "slack_thread",
        "confluence_page",
        "jira_ticket",
        "agent_memory",
        "other",
    ]
    title: str | None = None
    source_system: Literal[
        "upload",
        "s3",
        "slack",
        "confluence",
        "jira",
        "google_sheets",
        "csv",
        "pdf",
        "agent_conversation",
        "other",
    ]
    source_uri: str | None = None
    mime_type: str | None = None
    file_name: str | None = None
    raw_text: str | None = None
    structured_attributes: dict[str, AnyJson] | None = Field(
        default=None,
        description="Flexible structured metadata used for hybrid retrieval filters, e.g. product area, connector source, labels, timestamps.",
    )
    access: DocumentsDocumentAccess | None = Field(
        default=None,
        description="Optional access association carried at document level; included as current-state-aligned metadata, not as a separate entitlement system.",
    )
    ingest_status: Literal["uploaded", "text_extracted", "chunked", "embedded", "failed"]
    ingest_errors: list[dict[str, AnyJson]] | None = None
    is_agent_memory: bool
    created_at: UtcDatetime
    updated_at: UtcDatetime


class ChunkProfilesDocument(BaseModel):
    """Document in `chunk_profiles`. Definition of chunking strategies used in the POV/demo and benchmarking harness. Separated so the same document can be chunked multiple ways without duplicating strategy metadata on every chunk."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: PyObjectId | None = Field(default=None, alias="_id")
    tenant_id: PyObjectId | None = None
    name: str
    strategy: Literal["fixed_length", "recursive", "semantic", "contextual"]
    parameters: dict[str, AnyJson] | None = Field(
        default=None,
        description="Strategy-specific settings such as chunk_size, overlap, separators, semantic thresholds.",
    )
    is_active: bool
    created_at: UtcDatetime


class ChunksDocument(BaseModel):
    """Document in `chunks`. Retrieval unit derived from documents. Stores chunk text, chunking strategy used, embedding vector, and ranking metadata needed for semantic retrieval and reranking experiments."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: PyObjectId | None = Field(default=None, alias="_id")
    tenant_id: PyObjectId
    document_id: PyObjectId
    chunk_profile_id: PyObjectId
    chunk_index: int
    text: str
    token_count: int | None = None
    char_count: int | None = None
    embedding: list[float] | None = None
    embedding_model: str | None = None
    embedding_dimensions: int | None = None
    structured_attributes: dict[str, AnyJson] | None = Field(
        default=None,
        description="Metadata copied/derived from document for hybrid filtering at chunk retrieval time.",
    )
    rerank_text: str | None = Field(
        default=None,
        description="Optional text optimized for reranker input, if different from chunk text.",
    )
    created_at: UtcDatetime


class QueriesDocumentDocumentScope(BaseModel):
    """Embedded `document_scope`."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    document_ids: list[PyObjectId] | None = None
    source_systems: list[str] | None = None
    metadata_filters: dict[str, AnyJson] | None = None


class QueriesDocument(BaseModel):
    """Document in `queries`. User questions and benchmark prompts submitted against a tenant corpus. Captures both ad hoc demo questions and benchmark questions with optional ground truth linkage."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: PyObjectId | None = Field(default=None, alias="_id")
    tenant_id: PyObjectId
    benchmark_run_id: PyObjectId | None = None
    query_text: str
    query_type: Literal["ad_hoc", "benchmark"]
    expected_answer_text: str | None = None
    ground_truth_chunk_ids: list[PyObjectId] | None = None
    ground_truth_document_ids: list[PyObjectId] | None = None
    document_scope: QueriesDocumentDocumentScope | None = Field(
        default=None,
        description="Optional constraints for on-the-fly demo queries or benchmark subsets.",
    )
    created_by: str | None = None
    created_at: UtcDatetime


class BenchmarkRunsDocumentComparisonTargetsItem(BaseModel):
    """Item of `comparison_targets`."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    target_name: str
    target_type: Literal[
        "mongodb_voyage", "elastic", "opensearch", "qdrant", "rudimentary_baseline", "other"
    ]


class BenchmarkRunsDocument(BaseModel):
    """Document in `benchmark_runs`. A side-by-side POV evaluation execution context for a corpus, retrieval configuration, and comparison target(s). Captures the benchmark session the customer requested, including top-k metrics and latency measurements across approaches."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: PyObjectId | None = Field(default=None, alias="_id")
    tenant_id: PyObjectId
    name: str
    status: Literal["draft", "running", "completed", "failed"]
    comparison_targets: list[BenchmarkRunsDocumentComparisonTargetsItem] = Field(
        description="Systems being compared in the run."
    )
    chunk_profile_ids: list[PyObjectId] | None = None
    top_k_values: list[int]
    notes: str | None = None
    started_at: UtcDatetime | None = None
    completed_at: UtcDatetime | None = None
    created_at: UtcDatetime


class QueryResultsDocumentResultsItem(BaseModel):
    """Item of `results`."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    rank: int
    chunk_id: PyObjectId | None = None
    document_id: PyObjectId | None = None
    score: float | None = None
    rerank_score: float | None = None
    text_snippet: str | None = None
    source_title: str | None = None
    is_ground_truth_match: bool | None = None


class QueryResultsDocumentMetrics(BaseModel):
    """Embedded `metrics`."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    precision_at_k: dict[str, AnyJson] | None = None
    recall_at_k: dict[str, AnyJson] | None = None
    mrr: float | None = None
    ndcg: float | None = None


class QueryResultsDocument(BaseModel):
    """Document in `query_results`. Stores retrieval outputs and evaluation metrics per query per compared approach. This collection is the measurement backbone for precision/recall/top-k/latency comparisons requested in the POV."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: PyObjectId | None = Field(default=None, alias="_id")
    benchmark_run_id: PyObjectId | None = None
    query_id: PyObjectId
    tenant_id: PyObjectId
    approach: Literal[
        "mongodb_voyage", "elastic", "opensearch", "qdrant", "rudimentary_baseline", "other"
    ]
    chunk_profile_id: PyObjectId | None = None
    retrieval_mode: Literal["vector", "lexical", "hybrid"]
    latency_ms: float
    top_k_requested: int
    results: list[QueryResultsDocumentResultsItem] = Field(
        description="Ordered retrieval set for the query."
    )
    metrics: QueryResultsDocumentMetrics | None = Field(
        default=None, description="Evaluation metrics captured for this approach/query."
    )
    created_at: UtcDatetime
