"""All generated routers, mounted by app.main.create_app().

GENERATED by the backend coding agent - do not edit (read-only, verified by G8)."""

from __future__ import annotations

from fastapi import APIRouter

from app.api.routes.benchmark_runs import router as benchmark_runs_router
from app.api.routes.chunk_profiles import router as chunk_profiles_router
from app.api.routes.chunks import router as chunks_router
from app.api.routes.documents import router as documents_router
from app.api.routes.queries import router as queries_router
from app.api.routes.query_results import router as query_results_router
from app.api.routes.tenants import router as tenants_router

ROUTERS: list[APIRouter] = [
    tenants_router,
    documents_router,
    chunk_profiles_router,
    chunks_router,
    queries_router,
    benchmark_runs_router,
    query_results_router,
]
