"""Routes for `chunk_profiles`: validate input, call exactly one service method.

GENERATED by the backend coding agent - do not edit (read-only, verified by G8)."""

from __future__ import annotations

from typing import Annotated

from fastapi import APIRouter, Depends, Path

from app.api.deps import get_chunk_profiles_service
from app.api.schemas import (
    CreateChunkProfileRequest,
    CreateChunkProfileResponse,
    ListChunkProfilesResponse,
)
from app.api_error import ErrorBody
from app.services.chunk_profiles import ChunkProfilesService
from app.types import ObjectIdStr

router = APIRouter(tags=["chunk_profiles"])


@router.get(
    "/api/v1/tenants/{tenantId}/chunk-profiles",
    operation_id="listChunkProfiles",
    status_code=200,
    response_model=ListChunkProfilesResponse,
    responses={400: {"model": ErrorBody, "description": "INVALID_ID"}},
    summary="Retrieve active chunking strategies available for comparison in the POV.",
)
async def list_chunk_profiles(
    service: Annotated[ChunkProfilesService, Depends(get_chunk_profiles_service)],
    tenantId: Annotated[ObjectIdStr, Path(description="MongoDB ObjectId string")],
) -> ListChunkProfilesResponse:
    return await service.list_chunk_profiles(tenant_id=tenantId)


@router.post(
    "/api/v1/tenants/{tenantId}/chunk-profiles",
    operation_id="createChunkProfile",
    status_code=201,
    response_model=CreateChunkProfileResponse,
    responses={
        400: {"model": ErrorBody, "description": "VALIDATION_ERROR"},
        404: {"model": ErrorBody, "description": "TENANT_NOT_FOUND"},
    },
    summary="Create a tenant-specific chunk profile for benchmark or demo comparisons.",
)
async def create_chunk_profile(
    service: Annotated[ChunkProfilesService, Depends(get_chunk_profiles_service)],
    body: CreateChunkProfileRequest,
    tenantId: Annotated[ObjectIdStr, Path(description="MongoDB ObjectId string")],
) -> CreateChunkProfileResponse:
    return await service.create_chunk_profile(body=body, tenant_id=tenantId)
