"""Routes for `chunks`: validate input, call exactly one service method.

GENERATED by the backend coding agent - do not edit (read-only, verified by G8)."""

from __future__ import annotations

from typing import Annotated

from fastapi import APIRouter, Depends, Path, Query

from app.api.deps import get_chunks_service
from app.api.schemas import (
    GetDocumentChunksByProfileResponse,
    HybridSearchDocumentsRequest,
    HybridSearchDocumentsResponse,
    SearchAgentMemoryRequest,
    SearchAgentMemoryResponse,
    VectorSearchDocumentsRequest,
    VectorSearchDocumentsResponse,
)
from app.api_error import ErrorBody
from app.services.chunks import ChunksService
from app.types import ObjectIdStr

router = APIRouter(tags=["chunks"])


@router.get(
    "/api/v1/tenants/{tenantId}/documents/{documentId}/chunks",
    operation_id="getDocumentChunksByProfile",
    status_code=200,
    response_model=GetDocumentChunksByProfileResponse,
    responses={
        400: {"model": ErrorBody, "description": "VALIDATION_ERROR"},
        404: {"model": ErrorBody, "description": "DOCUMENT_NOT_FOUND"},
    },
    summary="Inspect ordered chunks for a document under a selected chunking strategy.",
)
async def get_document_chunks_by_profile(
    service: Annotated[ChunksService, Depends(get_chunks_service)],
    tenantId: Annotated[ObjectIdStr, Path(description="MongoDB ObjectId string")],
    documentId: Annotated[ObjectIdStr, Path(description="MongoDB ObjectId string")],
    chunk_profile_id: Annotated[ObjectIdStr, Query(description="MongoDB ObjectId string")],
) -> GetDocumentChunksByProfileResponse:
    return await service.get_document_chunks_by_profile(
        tenant_id=tenantId, document_id=documentId, chunk_profile_id=chunk_profile_id
    )


@router.post(
    "/api/v1/tenants/{tenantId}/search/vector",
    operation_id="vectorSearchDocuments",
    status_code=200,
    response_model=VectorSearchDocumentsResponse,
    responses={
        400: {"model": ErrorBody, "description": "VALIDATION_ERROR"},
        404: {"model": ErrorBody, "description": "CHUNK_PROFILE_NOT_FOUND"},
        422: {"model": ErrorBody, "description": "EMBEDDING_GENERATION_FAILED"},
    },
    summary="Run semantic vector retrieval over chunks for document search.",
)
async def vector_search_documents(
    service: Annotated[ChunksService, Depends(get_chunks_service)],
    body: VectorSearchDocumentsRequest,
    tenantId: Annotated[ObjectIdStr, Path(description="MongoDB ObjectId string")],
) -> VectorSearchDocumentsResponse:
    return await service.vector_search_documents(body=body, tenant_id=tenantId)


@router.post(
    "/api/v1/tenants/{tenantId}/search/hybrid",
    operation_id="hybridSearchDocuments",
    status_code=200,
    response_model=HybridSearchDocumentsResponse,
    responses={
        400: {"model": ErrorBody, "description": "VALIDATION_ERROR"},
        404: {"model": ErrorBody, "description": "CHUNK_PROFILE_NOT_FOUND"},
    },
    summary="Run lexical plus metadata-filtered retrieval over chunks to support hybrid structured and unstructured search.",
)
async def hybrid_search_documents(
    service: Annotated[ChunksService, Depends(get_chunks_service)],
    body: HybridSearchDocumentsRequest,
    tenantId: Annotated[ObjectIdStr, Path(description="MongoDB ObjectId string")],
) -> HybridSearchDocumentsResponse:
    return await service.hybrid_search_documents(body=body, tenant_id=tenantId)


@router.post(
    "/api/v1/tenants/{tenantId}/agent-memory/search",
    operation_id="searchAgentMemory",
    status_code=200,
    response_model=SearchAgentMemoryResponse,
    responses={
        400: {"model": ErrorBody, "description": "VALIDATION_ERROR"},
        404: {"model": ErrorBody, "description": "CHUNK_PROFILE_NOT_FOUND"},
        422: {"model": ErrorBody, "description": "EMBEDDING_GENERATION_FAILED"},
    },
    summary="Retrieve relevant conversation-derived memory chunks for an agent while honoring document access tags.",
)
async def search_agent_memory(
    service: Annotated[ChunksService, Depends(get_chunks_service)],
    body: SearchAgentMemoryRequest,
    tenantId: Annotated[ObjectIdStr, Path(description="MongoDB ObjectId string")],
) -> SearchAgentMemoryResponse:
    return await service.search_agent_memory(body=body, tenant_id=tenantId)
