"""Routes for `documents`: validate input, call exactly one service method.

GENERATED by the backend coding agent - do not edit (read-only, verified by G8)."""

from __future__ import annotations

from typing import Annotated

from fastapi import APIRouter, Depends, Path, Query
from pydantic import AwareDatetime

from app.api.deps import get_documents_service
from app.api.schemas import (
    CreateDocumentRequest,
    CreateDocumentResponse,
    GetDocumentResponse,
    ListDocumentIngestStatusesResponse,
    ListRetrievalReadyDocumentsResponse,
    UpdateDocumentRequest,
    UpdateDocumentResponse,
)
from app.api_error import ErrorBody
from app.services.documents import DocumentsService
from app.types import ObjectIdStr

router = APIRouter(tags=["documents"])


@router.post(
    "/api/v1/tenants/{tenantId}/documents",
    operation_id="createDocument",
    status_code=201,
    response_model=CreateDocumentResponse,
    responses={
        400: {"model": ErrorBody, "description": "VALIDATION_ERROR"},
        404: {"model": ErrorBody, "description": "TENANT_NOT_FOUND"},
    },
    summary="Create a document metadata record for uploaded content or conversation-derived memory. Raw binary upload is out of scope",
)
async def create_document(
    service: Annotated[DocumentsService, Depends(get_documents_service)],
    body: CreateDocumentRequest,
    tenantId: Annotated[ObjectIdStr, Path(description="MongoDB ObjectId string")],
) -> CreateDocumentResponse:
    return await service.create_document(body=body, tenant_id=tenantId)


@router.get(
    "/api/v1/tenants/{tenantId}/documents",
    operation_id="listRetrievalReadyDocuments",
    status_code=200,
    response_model=ListRetrievalReadyDocumentsResponse,
    responses={
        400: {"model": ErrorBody, "description": "VALIDATION_ERROR"},
        404: {"model": ErrorBody, "description": "TENANT_NOT_FOUND"},
    },
    summary="List retrieval-ready documents for a tenant demo session.",
)
async def list_retrieval_ready_documents(
    service: Annotated[DocumentsService, Depends(get_documents_service)],
    tenantId: Annotated[ObjectIdStr, Path(description="MongoDB ObjectId string")],
    ready_only: Annotated[bool, Query()] = True,
    document_types: Annotated[
        str | None, Query(description="comma-separated enum list, optional")
    ] = None,
    source_systems: Annotated[
        str | None, Query(description="comma-separated enum list, optional")
    ] = None,
    created_after: Annotated[AwareDatetime | None, Query()] = None,
    limit: Annotated[int | None, Query()] = None,
) -> ListRetrievalReadyDocumentsResponse:
    return await service.list_retrieval_ready_documents(
        tenant_id=tenantId,
        ready_only=ready_only,
        document_types=document_types,
        source_systems=source_systems,
        created_after=created_after,
        limit=limit,
    )


@router.get(
    "/api/v1/tenants/{tenantId}/documents/ingest-status",
    operation_id="listDocumentIngestStatuses",
    status_code=200,
    response_model=ListDocumentIngestStatusesResponse,
    responses={
        400: {"model": ErrorBody, "description": "VALIDATION_ERROR"},
        404: {"model": ErrorBody, "description": "TENANT_NOT_FOUND"},
    },
    summary="Inspect document ingest pipeline status and failures for a tenant.",
)
async def list_document_ingest_statuses(
    service: Annotated[DocumentsService, Depends(get_documents_service)],
    tenantId: Annotated[ObjectIdStr, Path(description="MongoDB ObjectId string")],
    created_after: Annotated[AwareDatetime | None, Query()] = None,
    limit: Annotated[int | None, Query()] = None,
) -> ListDocumentIngestStatusesResponse:
    return await service.list_document_ingest_statuses(
        tenant_id=tenantId, created_after=created_after, limit=limit
    )


@router.get(
    "/api/v1/tenants/{tenantId}/documents/{documentId}",
    operation_id="getDocument",
    status_code=200,
    response_model=GetDocumentResponse,
    responses={
        400: {"model": ErrorBody, "description": "INVALID_ID"},
        404: {"model": ErrorBody, "description": "DOCUMENT_NOT_FOUND"},
    },
    summary="Retrieve a single document record including ingest metadata and structured attributes.",
)
async def get_document(
    service: Annotated[DocumentsService, Depends(get_documents_service)],
    tenantId: Annotated[ObjectIdStr, Path(description="MongoDB ObjectId string")],
    documentId: Annotated[ObjectIdStr, Path(description="MongoDB ObjectId string")],
) -> GetDocumentResponse:
    return await service.get_document(tenant_id=tenantId, document_id=documentId)


@router.patch(
    "/api/v1/tenants/{tenantId}/documents/{documentId}",
    operation_id="updateDocument",
    status_code=200,
    response_model=UpdateDocumentResponse,
    responses={
        400: {"model": ErrorBody, "description": "VALIDATION_ERROR"},
        404: {"model": ErrorBody, "description": "DOCUMENT_NOT_FOUND"},
    },
    summary="Update document metadata, ingest status, extracted text, or access tags as processing progresses.",
)
async def update_document(
    service: Annotated[DocumentsService, Depends(get_documents_service)],
    body: UpdateDocumentRequest,
    tenantId: Annotated[ObjectIdStr, Path(description="MongoDB ObjectId string")],
    documentId: Annotated[ObjectIdStr, Path(description="MongoDB ObjectId string")],
) -> UpdateDocumentResponse:
    return await service.update_document(body=body, tenant_id=tenantId, document_id=documentId)
