"""Routes for `queries`: validate input, call exactly one service method.

GENERATED by the backend coding agent - do not edit (read-only, verified by G8)."""

from __future__ import annotations

from typing import Annotated

from fastapi import APIRouter, Depends, Path, Query
from pydantic import AwareDatetime

from app.api.deps import get_queries_service
from app.api.schemas import (
    CreateQueryRequest,
    CreateQueryResponse,
    ListBenchmarkQueriesResponse,
    ListRecentAdHocQueriesResponse,
)
from app.api_error import ErrorBody
from app.services.queries import QueriesService
from app.types import ObjectIdStr

router = APIRouter(tags=["queries"])


@router.post(
    "/api/v1/tenants/{tenantId}/queries",
    operation_id="createQuery",
    status_code=201,
    response_model=CreateQueryResponse,
    responses={
        400: {"model": ErrorBody, "description": "VALIDATION_ERROR"},
        404: {"model": ErrorBody, "description": "TENANT_NOT_FOUND | BENCHMARK_RUN_NOT_FOUND"},
    },
    summary="Create an ad hoc or benchmark query record before or alongside retrieval execution.",
)
async def create_query(
    service: Annotated[QueriesService, Depends(get_queries_service)],
    body: CreateQueryRequest,
    tenantId: Annotated[ObjectIdStr, Path(description="MongoDB ObjectId string")],
) -> CreateQueryResponse:
    return await service.create_query(body=body, tenant_id=tenantId)


@router.get(
    "/api/v1/tenants/{tenantId}/queries/history",
    operation_id="listRecentAdHocQueries",
    status_code=200,
    response_model=ListRecentAdHocQueriesResponse,
    responses={400: {"model": ErrorBody, "description": "VALIDATION_ERROR"}},
    summary="Show recent ad hoc query history for a tenant demo session.",
)
async def list_recent_ad_hoc_queries(
    service: Annotated[QueriesService, Depends(get_queries_service)],
    tenantId: Annotated[ObjectIdStr, Path(description="MongoDB ObjectId string")],
    created_after: Annotated[AwareDatetime | None, Query()] = None,
    limit: Annotated[int | None, Query()] = None,
) -> ListRecentAdHocQueriesResponse:
    return await service.list_recent_ad_hoc_queries(
        tenant_id=tenantId, created_after=created_after, limit=limit
    )


@router.get(
    "/api/v1/tenants/{tenantId}/benchmark-runs/{benchmarkRunId}/queries",
    operation_id="listBenchmarkQueries",
    status_code=200,
    response_model=ListBenchmarkQueriesResponse,
    responses={
        400: {"model": ErrorBody, "description": "INVALID_ID"},
        404: {"model": ErrorBody, "description": "BENCHMARK_RUN_NOT_FOUND"},
    },
    summary="List the benchmark question set and ground truth for a benchmark run.",
)
async def list_benchmark_queries(
    service: Annotated[QueriesService, Depends(get_queries_service)],
    tenantId: Annotated[ObjectIdStr, Path(description="MongoDB ObjectId string")],
    benchmarkRunId: Annotated[ObjectIdStr, Path(description="MongoDB ObjectId string")],
) -> ListBenchmarkQueriesResponse:
    return await service.list_benchmark_queries(tenant_id=tenantId, benchmark_run_id=benchmarkRunId)
