"""Routes for `tenants`: validate input, call exactly one service method.

GENERATED by the backend coding agent - do not edit (read-only, verified by G8)."""

from __future__ import annotations

from typing import Annotated, Literal

from fastapi import APIRouter, Depends, Path, Query

from app.api.deps import get_tenants_service
from app.api.schemas import (
    CreateTenantRequest,
    CreateTenantResponse,
    GetTenantResponse,
    ListTenantsResponse,
    UpdateTenantRequest,
    UpdateTenantResponse,
)
from app.api_error import ErrorBody
from app.services.tenants import TenantsService
from app.types import ObjectIdStr

router = APIRouter(tags=["tenants"])


@router.post(
    "/api/v1/tenants",
    operation_id="createTenant",
    status_code=201,
    response_model=CreateTenantResponse,
    responses={
        400: {"model": ErrorBody, "description": "VALIDATION_ERROR"},
        409: {"model": ErrorBody, "description": "TENANT_KEY_CONFLICT"},
    },
    summary="Create a tenant record used as the isolation boundary for demo documents, queries, and benchmark runs.",
)
async def create_tenant(
    service: Annotated[TenantsService, Depends(get_tenants_service)],
    body: CreateTenantRequest,
) -> CreateTenantResponse:
    return await service.create_tenant(body=body)


@router.get(
    "/api/v1/tenants",
    operation_id="listTenants",
    status_code=200,
    response_model=ListTenantsResponse,
    responses={400: {"model": ErrorBody, "description": "VALIDATION_ERROR"}},
    summary="List tenants available in the POV environment.",
)
async def list_tenants(
    service: Annotated[TenantsService, Depends(get_tenants_service)],
    status: Annotated[Literal["active", "inactive"] | None, Query()] = None,
    limit: Annotated[int | None, Query()] = None,
) -> ListTenantsResponse:
    return await service.list_tenants(status=status, limit=limit)


@router.get(
    "/api/v1/tenants/{tenantId}",
    operation_id="getTenant",
    status_code=200,
    response_model=GetTenantResponse,
    responses={
        400: {"model": ErrorBody, "description": "INVALID_ID"},
        404: {"model": ErrorBody, "description": "TENANT_NOT_FOUND"},
    },
    summary="Retrieve one tenant by id.",
)
async def get_tenant(
    service: Annotated[TenantsService, Depends(get_tenants_service)],
    tenantId: Annotated[ObjectIdStr, Path(description="MongoDB ObjectId string")],
) -> GetTenantResponse:
    return await service.get_tenant(tenant_id=tenantId)


@router.patch(
    "/api/v1/tenants/{tenantId}",
    operation_id="updateTenant",
    status_code=200,
    response_model=UpdateTenantResponse,
    responses={
        400: {"model": ErrorBody, "description": "VALIDATION_ERROR"},
        404: {"model": ErrorBody, "description": "TENANT_NOT_FOUND"},
        409: {"model": ErrorBody, "description": "TENANT_KEY_IMMUTABLE"},
    },
    summary="Update mutable tenant metadata.",
)
async def update_tenant(
    service: Annotated[TenantsService, Depends(get_tenants_service)],
    body: UpdateTenantRequest,
    tenantId: Annotated[ObjectIdStr, Path(description="MongoDB ObjectId string")],
) -> UpdateTenantResponse:
    return await service.update_tenant(body=body, tenant_id=tenantId)
