"""Service providers (FastAPI dependencies). Tests override these with fakes.

GENERATED by the backend coding agent - do not edit (read-only, verified by G8)."""

from __future__ import annotations

from typing import Annotated

from fastapi import Depends

from app.db.repositories import Repositories
from app.db.session import get_repositories
from app.services.benchmark_runs import BenchmarkRunsService
from app.services.chunk_profiles import ChunkProfilesService
from app.services.chunks import ChunksService
from app.services.documents import DocumentsService
from app.services.queries import QueriesService
from app.services.query_results import QueryResultsService
from app.services.tenants import TenantsService


def get_tenants_service(
    repos: Annotated[Repositories, Depends(get_repositories)],
) -> TenantsService:
    return TenantsService(repos)


def get_documents_service(
    repos: Annotated[Repositories, Depends(get_repositories)],
) -> DocumentsService:
    return DocumentsService(repos)


def get_chunk_profiles_service(
    repos: Annotated[Repositories, Depends(get_repositories)],
) -> ChunkProfilesService:
    return ChunkProfilesService(repos)


def get_chunks_service(repos: Annotated[Repositories, Depends(get_repositories)]) -> ChunksService:
    return ChunksService(repos)


def get_queries_service(
    repos: Annotated[Repositories, Depends(get_repositories)],
) -> QueriesService:
    return QueriesService(repos)


def get_benchmark_runs_service(
    repos: Annotated[Repositories, Depends(get_repositories)],
) -> BenchmarkRunsService:
    return BenchmarkRunsService(repos)


def get_query_results_service(
    repos: Annotated[Repositories, Depends(get_repositories)],
) -> QueryResultsService:
    return QueryResultsService(repos)
