"""Request/response models per operation (from api_contract).

GENERATED by the backend coding agent - do not edit (read-only, verified by G8)."""

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field

from app.types import AnyJson, ObjectIdStr, PyObjectId, UtcDatetime


class CreateTenantRequest(BaseModel):
    """Request body of createTenant (POST /api/v1/tenants)."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    tenant_key: str
    name: str
    deployment_model: Literal["shared", "isolated"] | None = None
    cloud: Literal["aws", "gcp", "azure", "other"] | None = None
    status: Literal["active", "inactive"]


class CreateTenantResponseTenant(BaseModel):
    """`tenant` of CreateTenantResponse."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: PyObjectId = Field(alias="_id", description="MongoDB ObjectId string")
    tenant_key: str
    name: str
    deployment_model: Literal["shared", "isolated"] | None = None
    cloud: Literal["aws", "gcp", "azure", "other"] | None = None
    status: Literal["active", "inactive"]
    created_at: UtcDatetime
    updated_at: UtcDatetime


class CreateTenantResponse(BaseModel):
    """Success (201) body of createTenant."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    tenant: CreateTenantResponseTenant


class ListTenantsResponseTenantsItem(BaseModel):
    """`tenants_item` of ListTenantsResponse."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: PyObjectId = Field(alias="_id", description="MongoDB ObjectId string")
    tenant_key: str
    name: str
    deployment_model: Literal["shared", "isolated"] | None = None
    cloud: Literal["aws", "gcp", "azure", "other"] | None = None
    status: Literal["active", "inactive"]
    created_at: UtcDatetime
    updated_at: UtcDatetime


class ListTenantsResponse(BaseModel):
    """Success (200) body of listTenants."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    tenants: list[ListTenantsResponseTenantsItem]


class GetTenantResponseTenant(BaseModel):
    """`tenant` of GetTenantResponse."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: PyObjectId = Field(alias="_id", description="MongoDB ObjectId string")
    tenant_key: str
    name: str
    deployment_model: Literal["shared", "isolated"] | None = None
    cloud: Literal["aws", "gcp", "azure", "other"] | None = None
    status: Literal["active", "inactive"]
    created_at: UtcDatetime
    updated_at: UtcDatetime


class GetTenantResponse(BaseModel):
    """Success (200) body of getTenant."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    tenant: GetTenantResponseTenant


class UpdateTenantRequest(BaseModel):
    """Request body of updateTenant (PATCH /api/v1/tenants/{tenantId})."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    name: str | None = None
    deployment_model: Literal["shared", "isolated"] | None = None
    cloud: Literal["aws", "gcp", "azure", "other"] | None = None
    status: Literal["active", "inactive"] | None = None


class UpdateTenantResponseTenant(BaseModel):
    """`tenant` of UpdateTenantResponse."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: PyObjectId = Field(alias="_id", description="MongoDB ObjectId string")
    tenant_key: str
    name: str
    deployment_model: Literal["shared", "isolated"] | None = None
    cloud: Literal["aws", "gcp", "azure", "other"] | None = None
    status: Literal["active", "inactive"]
    created_at: UtcDatetime
    updated_at: UtcDatetime


class UpdateTenantResponse(BaseModel):
    """Success (200) body of updateTenant."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    tenant: UpdateTenantResponseTenant


class CreateDocumentRequestAccess(BaseModel):
    """`access` of CreateDocumentRequest."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    user_ids: list[ObjectIdStr] | None = None
    group_ids: list[ObjectIdStr] | None = None


class CreateDocumentRequest(BaseModel):
    """Request body of createDocument (POST /api/v1/tenants/{tenantId}/documents)."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    document_type: Literal[
        "pdf",
        "csv",
        "google_sheet",
        "text",
        "slack_thread",
        "confluence_page",
        "jira_ticket",
        "agent_memory",
        "other",
    ]
    title: str | None = None
    source_system: Literal[
        "upload",
        "s3",
        "slack",
        "confluence",
        "jira",
        "google_sheets",
        "csv",
        "pdf",
        "agent_conversation",
        "other",
    ]
    source_uri: str | None = None
    mime_type: str | None = None
    file_name: str | None = None
    raw_text: str | None = None
    structured_attributes: dict[str, AnyJson] | None = None
    access: CreateDocumentRequestAccess | None = None
    ingest_status: Literal["uploaded", "text_extracted", "chunked", "embedded", "failed"]
    ingest_errors: list[dict[str, AnyJson]] | None = None
    is_agent_memory: bool


class CreateDocumentResponseDocumentAccess(BaseModel):
    """`access` of CreateDocumentResponseDocument."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    user_ids: list[PyObjectId]
    group_ids: list[PyObjectId]


class CreateDocumentResponseDocument(BaseModel):
    """`document` of CreateDocumentResponse."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: PyObjectId = Field(alias="_id", description="MongoDB ObjectId string")
    tenant_id: PyObjectId = Field(description="MongoDB ObjectId string")
    document_type: str
    title: str | None = None
    source_system: str
    source_uri: str | None = None
    mime_type: str | None = None
    file_name: str | None = None
    raw_text: str | None = None
    structured_attributes: dict[str, AnyJson] | None = None
    access: CreateDocumentResponseDocumentAccess
    ingest_status: str
    ingest_errors: list[dict[str, AnyJson]]
    is_agent_memory: bool
    created_at: UtcDatetime
    updated_at: UtcDatetime


class CreateDocumentResponse(BaseModel):
    """Success (201) body of createDocument."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    document: CreateDocumentResponseDocument


class ListRetrievalReadyDocumentsResponseDocumentsItem(BaseModel):
    """`documents_item` of ListRetrievalReadyDocumentsResponse."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: PyObjectId = Field(alias="_id", description="MongoDB ObjectId string")
    title: str | None = None
    file_name: str | None = None
    document_type: str
    source_system: str
    source_uri: str | None = None
    structured_attributes: dict[str, AnyJson] | None = None
    is_agent_memory: bool
    created_at: UtcDatetime


class ListRetrievalReadyDocumentsResponse(BaseModel):
    """Success (200) body of listRetrievalReadyDocuments."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    documents: list[ListRetrievalReadyDocumentsResponseDocumentsItem]


class ListDocumentIngestStatusesResponseDocumentsItem(BaseModel):
    """`documents_item` of ListDocumentIngestStatusesResponse."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: PyObjectId = Field(alias="_id", description="MongoDB ObjectId string")
    title: str | None = None
    file_name: str | None = None
    document_type: str
    source_system: str
    ingest_status: Literal["uploaded", "text_extracted", "chunked", "embedded", "failed"]
    ingest_errors: list[dict[str, AnyJson]]
    updated_at: UtcDatetime


class ListDocumentIngestStatusesResponse(BaseModel):
    """Success (200) body of listDocumentIngestStatuses."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    documents: list[ListDocumentIngestStatusesResponseDocumentsItem]


class GetDocumentResponseDocumentAccess(BaseModel):
    """`access` of GetDocumentResponseDocument."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    user_ids: list[PyObjectId]
    group_ids: list[PyObjectId]


class GetDocumentResponseDocument(BaseModel):
    """`document` of GetDocumentResponse."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: PyObjectId = Field(alias="_id", description="MongoDB ObjectId string")
    tenant_id: PyObjectId = Field(description="MongoDB ObjectId string")
    document_type: str
    title: str | None = None
    source_system: str
    source_uri: str | None = None
    mime_type: str | None = None
    file_name: str | None = None
    raw_text: str | None = None
    structured_attributes: dict[str, AnyJson] | None = None
    access: GetDocumentResponseDocumentAccess
    ingest_status: str
    ingest_errors: list[dict[str, AnyJson]]
    is_agent_memory: bool
    created_at: UtcDatetime
    updated_at: UtcDatetime


class GetDocumentResponse(BaseModel):
    """Success (200) body of getDocument."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    document: GetDocumentResponseDocument


class UpdateDocumentRequestAccess(BaseModel):
    """`access` of UpdateDocumentRequest."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    user_ids: list[ObjectIdStr] | None = None
    group_ids: list[ObjectIdStr] | None = None


class UpdateDocumentRequest(BaseModel):
    """Request body of updateDocument (PATCH /api/v1/tenants/{tenantId}/documents/{documentId})."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    title: str | None = None
    source_uri: str | None = None
    mime_type: str | None = None
    file_name: str | None = None
    raw_text: str | None = None
    structured_attributes: dict[str, AnyJson] | None = None
    access: UpdateDocumentRequestAccess | None = None
    ingest_status: Literal["uploaded", "text_extracted", "chunked", "embedded", "failed"] | None = (
        None
    )
    ingest_errors: list[dict[str, AnyJson]] | None = None


class UpdateDocumentResponseDocumentAccess(BaseModel):
    """`access` of UpdateDocumentResponseDocument."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    user_ids: list[PyObjectId]
    group_ids: list[PyObjectId]


class UpdateDocumentResponseDocument(BaseModel):
    """`document` of UpdateDocumentResponse."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: PyObjectId = Field(alias="_id", description="MongoDB ObjectId string")
    tenant_id: PyObjectId = Field(description="MongoDB ObjectId string")
    document_type: str
    title: str | None = None
    source_system: str
    source_uri: str | None = None
    mime_type: str | None = None
    file_name: str | None = None
    raw_text: str | None = None
    structured_attributes: dict[str, AnyJson] | None = None
    access: UpdateDocumentResponseDocumentAccess
    ingest_status: str
    ingest_errors: list[dict[str, AnyJson]]
    is_agent_memory: bool
    created_at: UtcDatetime
    updated_at: UtcDatetime


class UpdateDocumentResponse(BaseModel):
    """Success (200) body of updateDocument."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    document: UpdateDocumentResponseDocument


class ListChunkProfilesResponseChunkProfilesItem(BaseModel):
    """`chunk_profiles_item` of ListChunkProfilesResponse."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: PyObjectId = Field(alias="_id", description="MongoDB ObjectId string")
    name: str
    strategy: Literal["fixed_length", "recursive", "semantic", "contextual"]
    parameters: dict[str, AnyJson] | None = None
    tenant_id: PyObjectId | None = Field(default=None, description="MongoDB ObjectId string")


class ListChunkProfilesResponse(BaseModel):
    """Success (200) body of listChunkProfiles."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    chunk_profiles: list[ListChunkProfilesResponseChunkProfilesItem]


class CreateChunkProfileRequest(BaseModel):
    """Request body of createChunkProfile (POST /api/v1/tenants/{tenantId}/chunk-profiles)."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    name: str
    strategy: Literal["fixed_length", "recursive", "semantic", "contextual"]
    parameters: dict[str, AnyJson] | None = None
    is_active: bool


class CreateChunkProfileResponseChunkProfile(BaseModel):
    """`chunk_profile` of CreateChunkProfileResponse."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: PyObjectId = Field(alias="_id", description="MongoDB ObjectId string")
    tenant_id: PyObjectId = Field(description="MongoDB ObjectId string")
    name: str
    strategy: Literal["fixed_length", "recursive", "semantic", "contextual"]
    parameters: dict[str, AnyJson] | None = None
    is_active: bool
    created_at: UtcDatetime


class CreateChunkProfileResponse(BaseModel):
    """Success (201) body of createChunkProfile."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    chunk_profile: CreateChunkProfileResponseChunkProfile


class GetDocumentChunksByProfileResponseChunksItemChunkProfile(BaseModel):
    """`chunk_profile` of GetDocumentChunksByProfileResponseChunksItem."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    name: str
    strategy: Literal["fixed_length", "recursive", "semantic", "contextual"]
    parameters: dict[str, AnyJson] | None = None


class GetDocumentChunksByProfileResponseChunksItem(BaseModel):
    """`chunks_item` of GetDocumentChunksByProfileResponse."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: PyObjectId = Field(alias="_id", description="MongoDB ObjectId string")
    document_id: PyObjectId = Field(description="MongoDB ObjectId string")
    chunk_index: int
    text: str
    token_count: int | None = None
    char_count: int | None = None
    chunk_profile: GetDocumentChunksByProfileResponseChunksItemChunkProfile


class GetDocumentChunksByProfileResponse(BaseModel):
    """Success (200) body of getDocumentChunksByProfile."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    chunks: list[GetDocumentChunksByProfileResponseChunksItem]


class CreateQueryRequestDocumentScope(BaseModel):
    """`document_scope` of CreateQueryRequest."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    document_ids: list[ObjectIdStr] | None = None
    source_systems: list[str] | None = None
    metadata_filters: dict[str, AnyJson] | None = None


class CreateQueryRequest(BaseModel):
    """Request body of createQuery (POST /api/v1/tenants/{tenantId}/queries)."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    benchmark_run_id: ObjectIdStr | None = Field(
        default=None, description="MongoDB ObjectId string"
    )
    query_text: str
    query_type: Literal["ad_hoc", "benchmark"]
    expected_answer_text: str | None = None
    ground_truth_chunk_ids: list[ObjectIdStr] | None = None
    ground_truth_document_ids: list[ObjectIdStr] | None = None
    document_scope: CreateQueryRequestDocumentScope | None = None
    created_by: str | None = None


class CreateQueryResponseQuery(BaseModel):
    """`query` of CreateQueryResponse."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: PyObjectId = Field(alias="_id", description="MongoDB ObjectId string")
    tenant_id: PyObjectId = Field(description="MongoDB ObjectId string")
    benchmark_run_id: PyObjectId | None = Field(default=None, description="MongoDB ObjectId string")
    query_text: str
    query_type: Literal["ad_hoc", "benchmark"]
    expected_answer_text: str | None = None
    ground_truth_chunk_ids: list[PyObjectId]
    ground_truth_document_ids: list[PyObjectId]
    document_scope: dict[str, AnyJson] | None = None
    created_by: str | None = None
    created_at: UtcDatetime


class CreateQueryResponse(BaseModel):
    """Success (201) body of createQuery."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    query: CreateQueryResponseQuery


class ListRecentAdHocQueriesResponseQueriesItem(BaseModel):
    """`queries_item` of ListRecentAdHocQueriesResponse."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: PyObjectId = Field(alias="_id", description="MongoDB ObjectId string")
    query_text: str
    document_scope: dict[str, AnyJson] | None = None
    created_by: str | None = None
    created_at: UtcDatetime


class ListRecentAdHocQueriesResponse(BaseModel):
    """Success (200) body of listRecentAdHocQueries."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    queries: list[ListRecentAdHocQueriesResponseQueriesItem]


class ListBenchmarkQueriesResponseQueriesItem(BaseModel):
    """`queries_item` of ListBenchmarkQueriesResponse."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: PyObjectId = Field(alias="_id", description="MongoDB ObjectId string")
    query_text: str
    expected_answer_text: str | None = None
    ground_truth_chunk_ids: list[PyObjectId]
    ground_truth_document_ids: list[PyObjectId]
    document_scope: dict[str, AnyJson] | None = None
    created_at: UtcDatetime


class ListBenchmarkQueriesResponse(BaseModel):
    """Success (200) body of listBenchmarkQueries."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    queries: list[ListBenchmarkQueriesResponseQueriesItem]


class VectorSearchDocumentsRequest(BaseModel):
    """Request body of vectorSearchDocuments (POST /api/v1/tenants/{tenantId}/search/vector)."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    query_text: str = Field(
        description="required for traceability even when query_embedding is supplied"
    )
    query_embedding: list[float] | None = None
    chunk_profile_id: ObjectIdStr = Field(description="MongoDB ObjectId string")
    document_ids: list[ObjectIdStr] | None = None
    top_k: int
    num_candidates: int
    user_id: ObjectIdStr | None = Field(default=None, description="MongoDB ObjectId string")
    group_ids: list[ObjectIdStr] | None = None
    query_id: ObjectIdStr | None = Field(default=None, description="MongoDB ObjectId string")


class VectorSearchDocumentsResponseResultsItem(BaseModel):
    """`results_item` of VectorSearchDocumentsResponse."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    rank: int
    chunk_id: PyObjectId = Field(description="MongoDB ObjectId string")
    document_id: PyObjectId = Field(description="MongoDB ObjectId string")
    score: float
    text_snippet: str
    source_title: str | None = None
    document_type: str
    source_system: str
    structured_attributes: dict[str, AnyJson] | None = None


class VectorSearchDocumentsResponse(BaseModel):
    """Success (200) body of vectorSearchDocuments."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    query_id: PyObjectId | None = Field(default=None, description="MongoDB ObjectId string")
    retrieval_mode: Literal["vector"]
    results: list[VectorSearchDocumentsResponseResultsItem]


class HybridSearchDocumentsRequestDocumentScope(BaseModel):
    """`document_scope` of HybridSearchDocumentsRequest."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    document_ids: list[ObjectIdStr] | None = None
    source_systems: list[str] | None = None


class HybridSearchDocumentsRequest(BaseModel):
    """Request body of hybridSearchDocuments (POST /api/v1/tenants/{tenantId}/search/hybrid)."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    query_text: str
    chunk_profile_id: ObjectIdStr = Field(description="MongoDB ObjectId string")
    metadata_filters: dict[str, AnyJson] | None = None
    document_scope: HybridSearchDocumentsRequestDocumentScope | None = None
    top_k: int
    query_id: ObjectIdStr | None = Field(default=None, description="MongoDB ObjectId string")


class HybridSearchDocumentsResponseResultsItem(BaseModel):
    """`results_item` of HybridSearchDocumentsResponse."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    rank: int
    chunk_id: PyObjectId = Field(description="MongoDB ObjectId string")
    document_id: PyObjectId = Field(description="MongoDB ObjectId string")
    score: float
    text_snippet: str
    source_title: str | None = None
    document_type: str
    structured_attributes: dict[str, AnyJson] | None = None


class HybridSearchDocumentsResponse(BaseModel):
    """Success (200) body of hybridSearchDocuments."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    query_id: PyObjectId | None = Field(default=None, description="MongoDB ObjectId string")
    retrieval_mode: Literal["hybrid"]
    results: list[HybridSearchDocumentsResponseResultsItem]


class SearchAgentMemoryRequest(BaseModel):
    """Request body of searchAgentMemory (POST /api/v1/tenants/{tenantId}/agent-memory/search)."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    query_text: str = Field(
        description="required for traceability even when query_embedding is supplied"
    )
    query_embedding: list[float] | None = None
    chunk_profile_id: ObjectIdStr = Field(description="MongoDB ObjectId string")
    memory_type: str | None = None
    user_id: ObjectIdStr = Field(description="MongoDB ObjectId string")
    group_ids: list[ObjectIdStr] | None = None
    top_k: int
    num_candidates: int
    query_id: ObjectIdStr | None = Field(default=None, description="MongoDB ObjectId string")


class SearchAgentMemoryResponseResultsItem(BaseModel):
    """`results_item` of SearchAgentMemoryResponse."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    rank: int
    chunk_id: PyObjectId = Field(description="MongoDB ObjectId string")
    document_id: PyObjectId = Field(description="MongoDB ObjectId string")
    score: float
    text_snippet: str
    source_title: str | None = None
    structured_attributes: dict[str, AnyJson] | None = None
    created_at: UtcDatetime


class SearchAgentMemoryResponse(BaseModel):
    """Success (200) body of searchAgentMemory."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    query_id: PyObjectId | None = Field(default=None, description="MongoDB ObjectId string")
    retrieval_mode: Literal["vector"]
    results: list[SearchAgentMemoryResponseResultsItem]


class CreateBenchmarkRunRequestComparisonTargetsItem(BaseModel):
    """`comparison_targets_item` of CreateBenchmarkRunRequest."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    target_name: str
    target_type: Literal[
        "mongodb_voyage", "elastic", "opensearch", "qdrant", "rudimentary_baseline", "other"
    ]


class CreateBenchmarkRunRequest(BaseModel):
    """Request body of createBenchmarkRun (POST /api/v1/tenants/{tenantId}/benchmark-runs)."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    name: str
    status: Literal["draft", "running", "completed", "failed"]
    comparison_targets: list[CreateBenchmarkRunRequestComparisonTargetsItem]
    chunk_profile_ids: list[ObjectIdStr] | None = None
    top_k_values: list[int]
    notes: str | None = None
    started_at: AwareDatetime | None = None
    completed_at: AwareDatetime | None = None


class CreateBenchmarkRunResponseBenchmarkRunComparisonTargetsItem(BaseModel):
    """`comparison_targets_item` of CreateBenchmarkRunResponseBenchmarkRun."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    target_name: str
    target_type: str


class CreateBenchmarkRunResponseBenchmarkRun(BaseModel):
    """`benchmark_run` of CreateBenchmarkRunResponse."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: PyObjectId = Field(alias="_id", description="MongoDB ObjectId string")
    tenant_id: PyObjectId = Field(description="MongoDB ObjectId string")
    name: str
    status: Literal["draft", "running", "completed", "failed"]
    comparison_targets: list[CreateBenchmarkRunResponseBenchmarkRunComparisonTargetsItem]
    chunk_profile_ids: list[PyObjectId]
    top_k_values: list[int]
    notes: str | None = None
    started_at: UtcDatetime | None = None
    completed_at: UtcDatetime | None = None
    created_at: UtcDatetime


class CreateBenchmarkRunResponse(BaseModel):
    """Success (201) body of createBenchmarkRun."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    benchmark_run: CreateBenchmarkRunResponseBenchmarkRun


class ListBenchmarkRunsResponseBenchmarkRunsItemComparisonTargetsItem(BaseModel):
    """`comparison_targets_item` of ListBenchmarkRunsResponseBenchmarkRunsItem."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    target_name: str
    target_type: str


class ListBenchmarkRunsResponseBenchmarkRunsItem(BaseModel):
    """`benchmark_runs_item` of ListBenchmarkRunsResponse."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: PyObjectId = Field(alias="_id", description="MongoDB ObjectId string")
    name: str
    status: Literal["draft", "running", "completed", "failed"]
    comparison_targets: list[ListBenchmarkRunsResponseBenchmarkRunsItemComparisonTargetsItem]
    chunk_profile_ids: list[PyObjectId]
    top_k_values: list[int]
    started_at: UtcDatetime | None = None
    completed_at: UtcDatetime | None = None
    created_at: UtcDatetime


class ListBenchmarkRunsResponse(BaseModel):
    """Success (200) body of listBenchmarkRuns."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    benchmark_runs: list[ListBenchmarkRunsResponseBenchmarkRunsItem]


class GetBenchmarkRunDetailResponseBenchmarkRunComparisonTargetsItem(BaseModel):
    """`comparison_targets_item` of GetBenchmarkRunDetailResponseBenchmarkRun."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    target_name: str
    target_type: str


class GetBenchmarkRunDetailResponseBenchmarkRunChunkProfilesItem(BaseModel):
    """`chunk_profiles_item` of GetBenchmarkRunDetailResponseBenchmarkRun."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: PyObjectId = Field(alias="_id", description="MongoDB ObjectId string")
    name: str
    strategy: Literal["fixed_length", "recursive", "semantic", "contextual"]
    parameters: dict[str, AnyJson] | None = None


class GetBenchmarkRunDetailResponseBenchmarkRun(BaseModel):
    """`benchmark_run` of GetBenchmarkRunDetailResponse."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: PyObjectId = Field(alias="_id", description="MongoDB ObjectId string")
    name: str
    status: Literal["draft", "running", "completed", "failed"]
    comparison_targets: list[GetBenchmarkRunDetailResponseBenchmarkRunComparisonTargetsItem]
    top_k_values: list[int]
    notes: str | None = None
    started_at: UtcDatetime | None = None
    completed_at: UtcDatetime | None = None
    chunk_profiles: list[GetBenchmarkRunDetailResponseBenchmarkRunChunkProfilesItem]


class GetBenchmarkRunDetailResponse(BaseModel):
    """Success (200) body of getBenchmarkRunDetail."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    benchmark_run: GetBenchmarkRunDetailResponseBenchmarkRun


class UpdateBenchmarkRunRequestComparisonTargetsItem(BaseModel):
    """`comparison_targets_item` of UpdateBenchmarkRunRequest."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    target_name: str | None = None
    target_type: (
        Literal[
            "mongodb_voyage", "elastic", "opensearch", "qdrant", "rudimentary_baseline", "other"
        ]
        | None
    ) = None


class UpdateBenchmarkRunRequest(BaseModel):
    """Request body of updateBenchmarkRun (PATCH /api/v1/tenants/{tenantId}/benchmark-runs/{benchmarkRunId})."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    name: str | None = None
    status: Literal["draft", "running", "completed", "failed"] | None = None
    comparison_targets: list[UpdateBenchmarkRunRequestComparisonTargetsItem] | None = None
    chunk_profile_ids: list[ObjectIdStr] | None = None
    top_k_values: list[int] | None = None
    notes: str | None = None
    started_at: AwareDatetime | None = None
    completed_at: AwareDatetime | None = None


class UpdateBenchmarkRunResponseBenchmarkRunComparisonTargetsItem(BaseModel):
    """`comparison_targets_item` of UpdateBenchmarkRunResponseBenchmarkRun."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    target_name: str
    target_type: str


class UpdateBenchmarkRunResponseBenchmarkRun(BaseModel):
    """`benchmark_run` of UpdateBenchmarkRunResponse."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: PyObjectId = Field(alias="_id", description="MongoDB ObjectId string")
    tenant_id: PyObjectId = Field(description="MongoDB ObjectId string")
    name: str
    status: Literal["draft", "running", "completed", "failed"]
    comparison_targets: list[UpdateBenchmarkRunResponseBenchmarkRunComparisonTargetsItem]
    chunk_profile_ids: list[PyObjectId]
    top_k_values: list[int]
    notes: str | None = None
    started_at: UtcDatetime | None = None
    completed_at: UtcDatetime | None = None
    created_at: UtcDatetime


class UpdateBenchmarkRunResponse(BaseModel):
    """Success (200) body of updateBenchmarkRun."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    benchmark_run: UpdateBenchmarkRunResponseBenchmarkRun


class CreateQueryResultRequestResultsItem(BaseModel):
    """`results_item` of CreateQueryResultRequest."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    rank: int
    chunk_id: ObjectIdStr | None = Field(default=None, description="MongoDB ObjectId string")
    document_id: ObjectIdStr | None = Field(default=None, description="MongoDB ObjectId string")
    score: float | None = None
    rerank_score: float | None = None
    text_snippet: str | None = None
    source_title: str | None = None
    is_ground_truth_match: bool | None = None


class CreateQueryResultRequestMetrics(BaseModel):
    """`metrics` of CreateQueryResultRequest."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    precision_at_k: dict[str, AnyJson] | None = None
    recall_at_k: dict[str, AnyJson] | None = None
    mrr: float | None = None
    ndcg: float | None = None


class CreateQueryResultRequest(BaseModel):
    """Request body of createQueryResult (POST /api/v1/tenants/{tenantId}/query-results)."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    benchmark_run_id: ObjectIdStr | None = Field(
        default=None, description="MongoDB ObjectId string"
    )
    query_id: ObjectIdStr = Field(description="MongoDB ObjectId string")
    approach: Literal[
        "mongodb_voyage", "elastic", "opensearch", "qdrant", "rudimentary_baseline", "other"
    ]
    chunk_profile_id: ObjectIdStr | None = Field(
        default=None, description="MongoDB ObjectId string"
    )
    retrieval_mode: Literal["vector", "lexical", "hybrid"]
    latency_ms: float
    top_k_requested: int
    results: list[CreateQueryResultRequestResultsItem]
    metrics: CreateQueryResultRequestMetrics | None = None


class CreateQueryResultResponseQueryResult(BaseModel):
    """`query_result` of CreateQueryResultResponse."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    id: PyObjectId = Field(alias="_id", description="MongoDB ObjectId string")
    benchmark_run_id: PyObjectId | None = Field(default=None, description="MongoDB ObjectId string")
    query_id: PyObjectId = Field(description="MongoDB ObjectId string")
    tenant_id: PyObjectId = Field(description="MongoDB ObjectId string")
    approach: str
    chunk_profile_id: PyObjectId | None = Field(default=None, description="MongoDB ObjectId string")
    retrieval_mode: Literal["vector", "lexical", "hybrid"]
    latency_ms: float
    top_k_requested: int
    results: list[AnyJson]
    metrics: dict[str, AnyJson] | None = None
    created_at: UtcDatetime


class CreateQueryResultResponse(BaseModel):
    """Success (201) body of createQueryResult."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    query_result: CreateQueryResultResponseQueryResult


class GetBenchmarkQueryComparisonResponseComparisonsItemResultsItem(BaseModel):
    """`results_item` of GetBenchmarkQueryComparisonResponseComparisonsItem."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    rank: int
    chunk_id: PyObjectId | None = Field(default=None, description="MongoDB ObjectId string")
    document_id: PyObjectId | None = Field(default=None, description="MongoDB ObjectId string")
    score: float | None = None
    rerank_score: float | None = None
    text_snippet: str | None = None
    source_title: str | None = None
    is_ground_truth_match: bool | None = None


class GetBenchmarkQueryComparisonResponseComparisonsItemMetrics(BaseModel):
    """`metrics` of GetBenchmarkQueryComparisonResponseComparisonsItem."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    precision_at_k: dict[str, AnyJson] | None = None
    recall_at_k: dict[str, AnyJson] | None = None
    mrr: float | None = None
    ndcg: float | None = None


class GetBenchmarkQueryComparisonResponseComparisonsItemChunkProfile(BaseModel):
    """`chunk_profile` of GetBenchmarkQueryComparisonResponseComparisonsItem."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    name: str | None = None
    strategy: Literal["fixed_length", "recursive", "semantic", "contextual"] | None = None


class GetBenchmarkQueryComparisonResponseComparisonsItem(BaseModel):
    """`comparisons_item` of GetBenchmarkQueryComparisonResponse."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    approach: Literal[
        "mongodb_voyage", "elastic", "opensearch", "qdrant", "rudimentary_baseline", "other"
    ]
    retrieval_mode: Literal["vector", "lexical", "hybrid"]
    latency_ms: float
    top_k_requested: int
    results: list[GetBenchmarkQueryComparisonResponseComparisonsItemResultsItem]
    metrics: GetBenchmarkQueryComparisonResponseComparisonsItemMetrics
    chunk_profile: GetBenchmarkQueryComparisonResponseComparisonsItemChunkProfile


class GetBenchmarkQueryComparisonResponse(BaseModel):
    """Success (200) body of getBenchmarkQueryComparison."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    comparisons: list[GetBenchmarkQueryComparisonResponseComparisonsItem]


class GetBenchmarkSummaryResponseSummaryItem(BaseModel):
    """`summary_item` of GetBenchmarkSummaryResponse."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    approach: Literal[
        "mongodb_voyage", "elastic", "opensearch", "qdrant", "rudimentary_baseline", "other"
    ]
    retrieval_mode: Literal["vector", "lexical", "hybrid"]
    chunk_profile_id: PyObjectId | None = Field(default=None, description="MongoDB ObjectId string")
    top_k_requested: int
    avg_latency_ms: float
    query_count: int
    avg_mrr: float | None = None
    avg_ndcg: float | None = None
    avg_precision_at_1: float | None = None
    avg_precision_at_5: float | None = None
    avg_precision_at_10: float | None = None
    avg_precision_at_20: float | None = None
    avg_recall_at_1: float | None = None
    avg_recall_at_5: float | None = None
    avg_recall_at_10: float | None = None
    avg_recall_at_20: float | None = None


class GetBenchmarkSummaryResponse(BaseModel):
    """Success (200) body of getBenchmarkSummary."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    summary: list[GetBenchmarkSummaryResponseSummaryItem]


class GetBenchmarkWinsResponseWinsItemMongodbVoyage(BaseModel):
    """`mongodb_voyage` of GetBenchmarkWinsResponseWinsItem."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    approach: Literal["mongodb_voyage"]
    latency_ms: float | None = None
    mrr: float | None = None
    ndcg: float | None = None
    precision_at_5: float | None = None
    recall_at_5: float | None = None


class GetBenchmarkWinsResponseWinsItemBaseline(BaseModel):
    """`baseline` of GetBenchmarkWinsResponseWinsItem."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    approach: Literal["elastic", "opensearch", "qdrant", "rudimentary_baseline", "other"]
    latency_ms: float | None = None
    mrr: float | None = None
    ndcg: float | None = None
    precision_at_5: float | None = None
    recall_at_5: float | None = None


class GetBenchmarkWinsResponseWinsItem(BaseModel):
    """`wins_item` of GetBenchmarkWinsResponse."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    query_id: PyObjectId = Field(description="MongoDB ObjectId string")
    mongodb_voyage: GetBenchmarkWinsResponseWinsItemMongodbVoyage
    baseline: GetBenchmarkWinsResponseWinsItemBaseline
    is_better_on_mrr: bool
    is_better_on_ndcg: bool
    is_better_on_precision_at_5: bool
    is_better_on_recall_at_5: bool
    is_lower_latency: bool


class GetBenchmarkWinsResponse(BaseModel):
    """Success (200) body of getBenchmarkWins."""

    model_config = ConfigDict(extra="ignore", populate_by_name=True)

    wins: list[GetBenchmarkWinsResponseWinsItem]
