"""Contract error classes and validation-error code map (from api_contract).

GENERATED by the backend coding agent - do not edit (read-only, verified by G8)."""

from __future__ import annotations

from app.api_error import (
    ApiError,
    DatabaseUnavailable,
    DataShapeMismatch,
    DuplicateKeyConflict,
    InvalidRequest,
    NotImplementedOperation,
)


class ValidationError(ApiError):
    """400 VALIDATION_ERROR: Missing required fields or invalid enum values."""

    status_code = 400
    code = "VALIDATION_ERROR"
    default_message = "Missing required fields or invalid enum values."


class TenantKeyConflict(ApiError):
    """409 TENANT_KEY_CONFLICT: tenant_key already exists."""

    status_code = 409
    code = "TENANT_KEY_CONFLICT"
    default_message = "tenant_key already exists."


class InvalidId(ApiError):
    """400 INVALID_ID: tenantId is not a valid ObjectId."""

    status_code = 400
    code = "INVALID_ID"
    default_message = "tenantId is not a valid ObjectId."


class TenantNotFound(ApiError):
    """404 TENANT_NOT_FOUND: No tenant exists with the provided id."""

    status_code = 404
    code = "TENANT_NOT_FOUND"
    default_message = "No tenant exists with the provided id."


class TenantKeyImmutable(ApiError):
    """409 TENANT_KEY_IMMUTABLE: Attempt to update tenant_key through this endpoint."""

    status_code = 409
    code = "TENANT_KEY_IMMUTABLE"
    default_message = "Attempt to update tenant_key through this endpoint."


class DocumentNotFound(ApiError):
    """404 DOCUMENT_NOT_FOUND: No document exists for the tenant with the provided id."""

    status_code = 404
    code = "DOCUMENT_NOT_FOUND"
    default_message = "No document exists for the tenant with the provided id."


class BenchmarkRunNotFound(ApiError):
    """404 BENCHMARK_RUN_NOT_FOUND: benchmark_run_id is provided but does not exist for the tenant."""

    status_code = 404
    code = "BENCHMARK_RUN_NOT_FOUND"
    default_message = "benchmark_run_id is provided but does not exist for the tenant."


class ChunkProfileNotFound(ApiError):
    """404 CHUNK_PROFILE_NOT_FOUND: chunk_profile_id is invalid for the tenant/global scope."""

    status_code = 404
    code = "CHUNK_PROFILE_NOT_FOUND"
    default_message = "chunk_profile_id is invalid for the tenant/global scope."


class EmbeddingGenerationFailed(ApiError):
    """422 EMBEDDING_GENERATION_FAILED: Server-side embedding generation fails."""

    status_code = 422
    code = "EMBEDDING_GENERATION_FAILED"
    default_message = "Server-side embedding generation fails."


class QueryNotFound(ApiError):
    """404 QUERY_NOT_FOUND: query_id does not exist for the tenant."""

    status_code = 404
    code = "QUERY_NOT_FOUND"
    default_message = "query_id does not exist for the tenant."


class QueryOrRunNotFound(ApiError):
    """404 QUERY_OR_RUN_NOT_FOUND: No matching query/run exists for the tenant."""

    status_code = 404
    code = "QUERY_OR_RUN_NOT_FOUND"
    default_message = "No matching query/run exists for the tenant."


# Validation failures (FastAPI) are answered with 400 + the contract code mapped here.
VALIDATION_ERROR_CODES: dict[str, dict[str, str]] = {
    "createTenant": {"__default__": "VALIDATION_ERROR"},
    "listTenants": {"__default__": "VALIDATION_ERROR"},
    "getTenant": {"tenantId": "INVALID_ID", "__default__": "INVALID_ID"},
    "updateTenant": {"__default__": "VALIDATION_ERROR"},
    "createDocument": {"__default__": "VALIDATION_ERROR"},
    "listRetrievalReadyDocuments": {"__default__": "VALIDATION_ERROR"},
    "listDocumentIngestStatuses": {"__default__": "VALIDATION_ERROR"},
    "getDocument": {
        "tenantId": "INVALID_ID",
        "documentId": "INVALID_ID",
        "__default__": "INVALID_ID",
    },
    "updateDocument": {"__default__": "VALIDATION_ERROR"},
    "listChunkProfiles": {"tenantId": "INVALID_ID", "__default__": "INVALID_ID"},
    "createChunkProfile": {"__default__": "VALIDATION_ERROR"},
    "getDocumentChunksByProfile": {
        "chunk_profile_id": "VALIDATION_ERROR",
        "__default__": "VALIDATION_ERROR",
    },
    "createQuery": {"__default__": "VALIDATION_ERROR"},
    "listRecentAdHocQueries": {"__default__": "VALIDATION_ERROR"},
    "listBenchmarkQueries": {
        "tenantId": "INVALID_ID",
        "benchmarkRunId": "INVALID_ID",
        "__default__": "INVALID_ID",
    },
    "vectorSearchDocuments": {
        "query_embedding": "VALIDATION_ERROR",
        "__default__": "VALIDATION_ERROR",
    },
    "hybridSearchDocuments": {"__default__": "VALIDATION_ERROR"},
    "searchAgentMemory": {"__default__": "VALIDATION_ERROR"},
    "createBenchmarkRun": {"__default__": "VALIDATION_ERROR"},
    "listBenchmarkRuns": {"__default__": "VALIDATION_ERROR"},
    "getBenchmarkRunDetail": {
        "tenantId": "INVALID_ID",
        "benchmarkRunId": "INVALID_ID",
        "__default__": "INVALID_ID",
    },
    "updateBenchmarkRun": {"__default__": "VALIDATION_ERROR"},
    "createQueryResult": {"__default__": "VALIDATION_ERROR"},
    "getBenchmarkQueryComparison": {"__default__": "INVALID_ID"},
    "getBenchmarkSummary": {
        "tenantId": "INVALID_ID",
        "benchmarkRunId": "INVALID_ID",
        "__default__": "INVALID_ID",
    },
    "getBenchmarkWins": {
        "tenantId": "INVALID_ID",
        "benchmarkRunId": "INVALID_ID",
        "__default__": "INVALID_ID",
    },
}

# Errors each operation may raise (status, code) - services must raise only these.
ERRORS_BY_OPERATION: dict[str, list[type[ApiError]]] = {
    "createTenant": [ValidationError, TenantKeyConflict],
    "listTenants": [ValidationError],
    "getTenant": [InvalidId, TenantNotFound],
    "updateTenant": [ValidationError, TenantNotFound, TenantKeyImmutable],
    "createDocument": [ValidationError, TenantNotFound],
    "listRetrievalReadyDocuments": [ValidationError, TenantNotFound],
    "listDocumentIngestStatuses": [ValidationError, TenantNotFound],
    "getDocument": [InvalidId, DocumentNotFound],
    "updateDocument": [ValidationError, DocumentNotFound],
    "listChunkProfiles": [InvalidId],
    "createChunkProfile": [ValidationError, TenantNotFound],
    "getDocumentChunksByProfile": [ValidationError, DocumentNotFound],
    "createQuery": [ValidationError, TenantNotFound, BenchmarkRunNotFound],
    "listRecentAdHocQueries": [ValidationError],
    "listBenchmarkQueries": [InvalidId, BenchmarkRunNotFound],
    "vectorSearchDocuments": [ValidationError, ChunkProfileNotFound, EmbeddingGenerationFailed],
    "hybridSearchDocuments": [ValidationError, ChunkProfileNotFound],
    "searchAgentMemory": [ValidationError, ChunkProfileNotFound, EmbeddingGenerationFailed],
    "createBenchmarkRun": [ValidationError, TenantNotFound],
    "listBenchmarkRuns": [ValidationError],
    "getBenchmarkRunDetail": [InvalidId, BenchmarkRunNotFound],
    "updateBenchmarkRun": [ValidationError, BenchmarkRunNotFound],
    "createQueryResult": [ValidationError, QueryNotFound, BenchmarkRunNotFound],
    "getBenchmarkQueryComparison": [InvalidId, QueryOrRunNotFound],
    "getBenchmarkSummary": [InvalidId, BenchmarkRunNotFound],
    "getBenchmarkWins": [InvalidId, BenchmarkRunNotFound],
}

__all__ = [
    "ERRORS_BY_OPERATION",
    "VALIDATION_ERROR_CODES",
    "ApiError",
    "BenchmarkRunNotFound",
    "ChunkProfileNotFound",
    "DataShapeMismatch",
    "DatabaseUnavailable",
    "DocumentNotFound",
    "DuplicateKeyConflict",
    "EmbeddingGenerationFailed",
    "InvalidId",
    "InvalidRequest",
    "NotImplementedOperation",
    "QueryNotFound",
    "QueryOrRunNotFound",
    "TenantKeyConflict",
    "TenantKeyImmutable",
    "TenantNotFound",
    "ValidationError",
]
